export interface LearningSessionCompletedEvent { sessionId:string; userId?:string; accuracy:number; activityType:string; conceptsDemonstrated?:string[]; masteryChanges?:Record<string,number>; xpGained?:number; hintsUsed?:boolean; }
export interface AppEventMap {
 'learning:sessionCompleted':LearningSessionCompletedEvent;
 'quest:completed':{questId:string;userId:string}; 'story:progressed':{storyId:string;node:string;userId:string}; 'achievement:earned':{achievementId:string;userId:string;context?:Record<string,unknown>}; 'location:unlocked':{locationId:string;userId:string}; 'world:locationChanged':{locationId:string;userId:string;previousLocationId?:string}; 'conversation:completed':{conversationId:string;userId:string}; 'discovery:made':{discoveryId:string;type:string;ref:string;userId:string};
 'world:eventStarted':{eventId:string;worldId:string}; 'world:eventResolved':{eventId:string;choiceId:string;userId:string}; 'world:returned':{userId:string;lastActiveAt:string}; 'world:residentEncountered':{residentId:string;residentName:string;activity:string;locationId:string;userId:string}; 'world:residentMoment':{residentId:string;residentName:string;choice:string;userId:string};
 'world:destinationEntered':{kind:'journey';worldId:string;placeId:string;label:string}; 'world:returnHome':{kind:'home';worldId:'emerald-valley';label:'Emerald Valley'}; 'world:destinationLifeShifted':{worldId:string;placeId:string;elapsedMinutes:number;visits:number;phase:'first-visit'|'recent'|'returning'|'long-away'}; 'world:livingStateChanged':{userId:string;previousLocationId:string|null;locationId:string}; 'world:learningOutcomeResolved':{worldId:string;placeId:string;scenarioId:string;success:boolean;worldChange:string}; 'world:learningRelationshipChanged':{residentId:string;worldId:string;placeId:string;success:boolean;tone:'new'|'familiar'|'warm'|'trusted';familiarity:number;trust:number};
 'cassidy:autonomyActed':{action:'observe'|'join'|'suggest'|'help'|'celebrate'|'wander'|'live';mood:string;priority:number;canInterrupt:boolean;lifeActivity?:string;invitation?:boolean;visualAction?:'idle'|'talking'|'waving'|'walking';worldId?:string;destinationId?:string};
 'cassidy:narrativeCreated':{id:string;userId:string;kind:'dream'|'story'|'adventure';title:string;premise:string;worldId:string;destinationId?:string;createdAt:string;completedAt?:string;steps:string[];invitation?:boolean};
 'memory:recorded':{memoryId:string;layer:string;userId:string}; }
export type AppEventName=keyof AppEventMap; export type AppEventPayload<K extends AppEventName>=AppEventMap[K]; export type EventProducer='world'|'learning'|'quest'|'story'|'character'|'journey'|'discovery'|'system'|'cassidy';