export type CassidyExpression='neutral'|'happy'|'curious'|'surprised'|'thoughtful'|'excited'|'concerned'|'playful';
export type CassidyAnimation='idle'|'walk'|'run'|'turn'|'sit'|'talk'|'gesture'|'point'|'celebrate'|'think'|'react';
export type CassidyOutfitVariant='base'|'spring'|'summer'|'autumn'|'winter'|'emerald-valley'|'japanese-world'|'french-world'|'festival'|'adventure';
export type CassidyMaterialSlot='skin'|'hair'|'eyes'|'brows'|'outfit'|'shoes'|'accessory';
export interface CassidyCharacterIdentity{ id:'cassidy'; name:'Cassidy'; role:'world-companion'; silhouette:string; signatureDetails:string[]; face:{shape:string;eyeDesign:string;irisMaterial:string;hairDesign:string;expressionRange:string}; body:{proportionProfile:string;hands:string;feet:string;rigRequirement:string}; materials:Record<CassidyMaterialSlot,{description:string;consistencyKey:string}>;}
export interface CassidyCharacterAssetSet{model3dUri?:string;previewUri?:string;thumbnailUri?:string;rigVersion:string;textureVersion:string;animationVersion:string;validatedAngles:string[];validatedExpressions:CassidyExpression[];validatedAnimations:CassidyAnimation[];}
export interface CassidyCharacterState{expression:CassidyExpression;animation:CassidyAnimation;outfit:CassidyOutfitVariant;worldId:string;locationId?:string;visible:boolean;interactionLocked:boolean;updatedAt:number;}
export const CASSIDY_CHARACTER_IDENTITY: CassidyCharacterIdentity={id:'cassidy',name:'Cassidy',role:'world-companion',silhouette:'Distinctive full-body companion silhouette with a readable head-to-foot profile and stable proportions across cameras.',signatureDetails:['recognizable hairstyle','expressive eyes','consistent facial proportions','signature outfit language','clean hands and feet','subtle companion accessory'],face:{shape:'friendly stylized human face with deliberate proportions',eyeDesign:'large expressive eyes with controlled highlights and consistent spacing',irisMaterial:'high-quality physically coherent iris material',hairDesign:'layered hairstyle with intentional silhouette and strand groups',expressionRange:'eight authored expressions plus animation-driven micro-expression transitions'},body:{proportionProfile:'production character proportion sheet; never inferred independently per asset',hands:'fully modeled articulated hands with authored neutral and gesture poses',feet:'fully modeled feet with stable shoe contact and clean silhouettes',rigRequirement:'full-body articulated character rig suitable for locomotion, gestures and seated poses'},materials:{skin:{description:'clean stylized skin material with stable tone and controlled roughness',consistencyKey:'cassidy-skin-v1'},hair:{description:'layered hair material with controlled sheen and readable strand groups',consistencyKey:'cassidy-hair-v1'},eyes:{description:'multi-layer eye material with sclera, iris and corneal highlight',consistencyKey:'cassidy-eyes-v1'},brows:{description:'authored brow shapes supporting expression readability',consistencyKey:'cassidy-brows-v1'},outfit:{description:'production clothing materials with seams, folds and world-safe variants',consistencyKey:'cassidy-outfit-v1'},shoes:{description:'clean footwear geometry with stable ground contact',consistencyKey:'cassidy-shoes-v1'},accessory:{description:'optional signature accessory constrained by the character bible',consistencyKey:'cassidy-accessory-v1'}}};
export const CASSIDY_EXPRESSIONS:ReadonlyArray<CassidyExpression>=['neutral','happy','curious','surprised','thoughtful','excited','concerned','playful'];
export const CASSIDY_ANIMATIONS:ReadonlyArray<CassidyAnimation>=['idle','walk','run','turn','sit','talk','gesture','point','celebrate','think','react'];
export const CASSIDY_OUTFITS:ReadonlyArray<CassidyOutfitVariant>=['base','spring','summer','autumn','winter','emerald-valley','japanese-world','french-world','festival','adventure'];
export function createCassidyCharacterState(partial:Partial<CassidyCharacterState>={}):CassidyCharacterState{return{expression:partial.expression??'neutral',animation:partial.animation??'idle',outfit:partial.outfit??'base',worldId:partial.worldId??'emerald-valley',locationId:partial.locationId,visible:partial.visible??true,interactionLocked:partial.interactionLocked??false,updatedAt:Date.now()};}
