import React,{useEffect,useRef,useState}from'react';
import{Animated,Easing,Pressable,ScrollView,Text,View,Dimensions}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{auth}from'../../../services/auth';
import{livingWorldObjectsStore}from'../../../engines/world/livingWorldObjectsStore';
import{Cassidy,CassidyMood}from'../../../characters/cassidy';
import{CassidyVisualPresence}from'../components/CassidyVisualPresence';
import{Radio,BookOpen}from'lucide-react-native';

type Action='idle'|'talking'|'waving';
type Focus='left'|'right'|'center';
type Period='morning'|'afternoon'|'evening'|'night';
function resolvePeriod():Period{const h=new Date().getHours();if(h<5)return'night';if(h<12)return'morning';if(h<17)return'afternoon';if(h<20)return'evening';return'night'}
const THEME:Record<Period,{wall:string;sky:string;orb:string;orbRight:number;orbTop:number;lamp:number;word:string}>=
{morning:{wall:'#3a3357',sky:'#fde6b8',orb:'#fff0c0',orbRight:-3,orbTop:3,lamp:.08,word:'morning'},afternoon:{wall:'#473a63',sky:'#cfe8f7',orb:'#fff6d8',orbRight:6,orbTop:-2,lamp:.04,word:'afternoon'},evening:{wall:'#3a2c4d',sky:'#f7c79b',orb:'#ffd9a0',orbRight:8,orbTop:6,lamp:.32,word:'evening'},night:{wall:'#241d38',sky:'#33406b',orb:'#dfe6ff',orbRight:10,orbTop:2,lamp:.5,word:'night'}};

export function CassidyHomeScreen(){
 const[objects,setObjects]=useState<any[]>([]);const[action,setAction]=useState<Action>('idle');const[mood,setMood]=useState<CassidyMood>('warm');const[focus,setFocus]=useState<Focus>('center');const[speech,setSpeech]=useState<string|null>(Cassidy.pickGreeting());const[period,setPeriod]=useState<Period>(resolvePeriod);
 const roomIn=useRef(new Animated.Value(0)).current;const speechIn=useRef(new Animated.Value(0)).current;const radioPulse=useRef(new Animated.Value(0)).current;const bonsaiMotion=useRef(new Animated.Value(0)).current;const windowDrift=useRef(new Animated.Value(0)).current;
 useEffect(()=>{let active=true;const refresh=async()=>{try{const user=await auth.getCurrentUser();const userId=user?.id??'local-explorer-user';await livingWorldObjectsStore.migrateLegacyLocalState(userId);const next=await livingWorldObjectsStore.getAll(userId);if(active)setObjects(next)}catch{if(active)setObjects([])}};void refresh();const id=setInterval(()=>void refresh(),30000);return()=>{active=false;clearInterval(id)}},[]);
 useEffect(()=>{const sync=()=>setPeriod(resolvePeriod());sync();const id=setInterval(sync,60000);return()=>clearInterval(id)},[]);
 useEffect(()=>{Animated.spring(roomIn,{toValue:1,damping:20,stiffness:80,mass:.9,useNativeDriver:true}).start();const radio=Animated.loop(Animated.sequence([Animated.timing(radioPulse,{toValue:1,duration:1800,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(radioPulse,{toValue:0,duration:1800,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));const tree=Animated.loop(Animated.sequence([Animated.timing(bonsaiMotion,{toValue:1,duration:2600,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(bonsaiMotion,{toValue:-1,duration:3300,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(bonsaiMotion,{toValue:0,duration:1900,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));const sky=Animated.loop(Animated.sequence([Animated.timing(windowDrift,{toValue:1,duration:9000,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(windowDrift,{toValue:0,duration:9000,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));radio.start();tree.start();sky.start();return()=>{radio.stop();tree.stop();sky.stop()}},[bonsaiMotion,radioPulse,roomIn,windowDrift]);
 useEffect(()=>{const id=setInterval(()=>{setFocus(current=>{const next:Focus=current==='center'?'left':current==='left'?'right':'center';return next});setAction(current=>current==='idle'?'waving':'idle')},9500);return()=>clearInterval(id)},[]);
 useEffect(()=>{Animated.spring(speechIn,{toValue:speech?1:0,damping:18,stiffness:120,mass:.7,useNativeDriver:true}).start()},[speech,speechIn]);
 const t=THEME[period],bonsai=objects.find(o=>o.id==='living-bonsai'),radio=objects.find(o=>o.id==='living-radio'),bonsaiSize=46+(bonsai?Math.round((bonsai.growth/100)*34):0);
 const say=(line:string,act:Action='talking',m:CassidyMood='happy',nextFocus:Focus='center')=>{setSpeech(null);setMood(m);setFocus(nextFocus);setAction(act);requestAnimationFrame(()=>setSpeech(line));setTimeout(()=>setAction('idle'),act==='waving'?2200:3000)};
 const radioScale=radioPulse.interpolate({inputRange:[0,1],outputRange:[1,1.035]});const radioOpacity=radioPulse.interpolate({inputRange:[0,1],outputRange:[.3,.7]});const treeRotate=bonsaiMotion.interpolate({inputRange:[-1,0,1],outputRange:['-2deg','0deg','2deg']});const skyX=windowDrift.interpolate({inputRange:[0,1],outputRange:[-8,8]});const roomY=roomIn.interpolate({inputRange:[0,1],outputRange:[14,0]});
 return <SafeAreaView className="flex-1 bg-transparent"><ScrollView className="flex-1" contentContainerStyle={{paddingBottom:100}}><Animated.View className="relative" style={{minHeight:Dimensions.get('window').height-160,opacity:roomIn,transform:[{translateY:roomY}]}}><View className="h-[58%]" style={{backgroundColor:t.wall}}/><View className="h-[42%] bg-[#4a3a2c]"/>
  <View className="absolute left-6 top-10 h-36 w-28 overflow-hidden rounded-2xl border-2 border-[#6b5a8a]" style={{backgroundColor:t.sky}}><Animated.View className="absolute inset-y-0 w-40" style={{transform:[{translateX:skyX}]}}><View className="absolute h-10 w-10 rounded-full opacity-90" style={{right:t.orbRight,top:t.orbTop,backgroundColor:t.orb}}/><View className="absolute bottom-0 left-0 right-0 h-10 bg-[#b9d6e8] opacity-50"/></Animated.View><View className="absolute left-1/2 top-0 bottom-0 w-0.5 bg-[#6b5a8a] opacity-60"/><View className="absolute top-1/2 left-0 right-0 h-0.5 bg-[#6b5a8a] opacity-60"/></View>
  <View className="absolute right-5 top-12 flex-row items-end gap-5"><View className="items-center opacity-70"><BookOpen size={17} color="#cbb89a"/><Text className="mt-0.5 text-[8px] text-[#cbb89a]">books</Text></View><Pressable onPress={()=>say(radio?'The radio is still playing. I think it knows you are here.':'The radio is quiet today. Maybe we should leave it that way.','talking','warm','right')} className="items-center"><Animated.View style={{transform:[{scale:radioScale}]}}><Radio size={18} color={radio?'#34d399':'#8a7a66'}/></Animated.View><Animated.View className="absolute -inset-2 rounded-full border border-emerald-400" style={{opacity:radioOpacity}}/><Text className="mt-0.5 text-[8px] text-[#cbb89a]">radio</Text></Pressable></View>
  <View className="absolute bottom-24 left-1/2 h-6 w-72 -translate-x-1/2 rounded-full bg-[#6b4f8a] opacity-50"/>
  <Pressable onPress={()=>say(bonsai?`The bonsai is at ${bonsai.growth}% now. It grows a little as our world changes.`:'I keep a little bonsai here. It grows when you practice.','talking','warm','left')} className="absolute bottom-28 left-8 items-center"><Animated.View style={{transform:[{rotate:treeRotate}],transformOrigin:'50% 100%'}}><View className="items-center justify-end rounded-t-full bg-[#3f6b3f]" style={{width:bonsaiSize,height:bonsaiSize*.7}}/><View className="mt-1 h-5 w-8 rounded-b-md bg-[#7a4a2c]"/></Animated.View><Text className="mt-1 text-[8px] text-emerald-200">bonsai {bonsai?`${bonsai.growth}%`:''}</Text></Pressable>
  <Animated.View className="absolute bottom-16 left-1/2 -translate-x-1/2 items-center" style={{transform:[{translateX:-50},{translateY:0}]}}>{speech&&<Animated.View pointerEvents="none" style={{opacity:speechIn,transform:[{translateY:speechIn.interpolate({inputRange:[0,1],outputRange:[6,0]})}]}}><Text className="mb-2 max-w-[260px] text-center text-[12px] italic text-emerald-100">{speech}</Text></Animated.View>}<Pressable onPress={()=>say(Cassidy.lineFor('happy'),'waving','happy','center')} className="active:opacity-80"><CassidyVisualPresence height={230} action={action} speaking={action==='talking'} expression={mood} focus={focus} worldId="emerald-valley"/></Pressable><Text className="mt-1 text-[11px] font-semibold text-emerald-300">Cassidy</Text><Text className="text-[9px] text-slate-400">{t.word} · she notices when the world changes</Text></Animated.View>
  <View className="absolute right-10 top-40 h-24 w-24 rounded-full bg-amber-300" style={{opacity:t.lamp}} pointerEvents="none"/>
 </Animated.View></ScrollView></SafeAreaView>;
}
