export type LanguageWorldId='ja'|'es'|'fr'|'ko';
export type LanguageWorld={id:LanguageWorldId;languageCode:string;languageName:string;worldName:string;regionLabel:string;visualIdentity:string;places:{id:string;name:string;purpose:string}[];culture:{greetings:string[];food:string[];dailyLife:string[]};};

const WORLDS:Record<LanguageWorldId,LanguageWorld>={
 ja:{id:'ja',languageCode:'ja',languageName:'Japanese',worldName:'Hikari Isles',regionLabel:'Japan-inspired island cities',visualIdentity:'lantern-lit streets, mountain shrines, compact city neighborhoods, gardens and seasonal festivals',places:[{id:'neighborhood',name:'Midoricho',purpose:'daily conversation and routines'},{id:'market',name:'Tsuki Market',purpose:'shopping and numbers'},{id:'station',name:'Hikari Station',purpose:'directions and travel'},{id:'library',name:'Koto Archive',purpose:'reading and culture'}],culture:{greetings:['こんにちは','おはよう'],food:['お茶','おにぎり'],dailyLife:['commuting','shopping','seasonal festivals']}},
 es:{id:'es',languageCode:'es',languageName:'Spanish',worldName:'Solara',regionLabel:'Spanish-speaking coastal city world',visualIdentity:'sunlit plazas, colorful streets, cafés, markets, courtyards and coastal neighborhoods',places:[{id:'plaza',name:'Plaza del Sol',purpose:'social conversation'},{id:'market',name:'Mercado Vivo',purpose:'shopping and food'},{id:'harbor',name:'Puerto Claro',purpose:'travel and directions'},{id:'cafe',name:'Casa de Café',purpose:'ordering and everyday conversation'}],culture:{greetings:['hola','buenos días'],food:['pan','café'],dailyLife:['markets','family meals','city festivals']}},
 fr:{id:'fr',languageCode:'fr',languageName:'French',worldName:'Belle Rivière',regionLabel:'French riverside city world',visualIdentity:'riverside streets, stone architecture, bakeries, cafés, bookshops and evening lights',places:[{id:'square',name:'Place des Lumières',purpose:'conversation and social life'},{id:'bakery',name:'Boulangerie Matin',purpose:'food and ordering'},{id:'station',name:'Gare Rivière',purpose:'travel and directions'},{id:'bookshop',name:'Librairie des Rêves',purpose:'reading and culture'}],culture:{greetings:['bonjour','bonsoir'],food:['pain','fromage'],dailyLife:['cafés','markets','riverside evenings']}},
 ko:{id:'ko',languageCode:'ko',languageName:'Korean',worldName:'Haenam',regionLabel:'Korean city and mountain world',visualIdentity:'dense neighborhood streets, mountain views, neon evenings, traditional alleys, food stalls and seasonal celebrations',places:[{id:'alley',name:'Mirae Alley',purpose:'everyday conversation'},{id:'foodstreet',name:'Bada Food Street',purpose:'ordering and food vocabulary'},{id:'subway',name:'Haenam Metro',purpose:'travel and directions'},{id:'study',name:'Haneul Study House',purpose:'reading and culture'}],culture:{greetings:['안녕하세요','좋은 아침'],food:['김밥','차'],dailyLife:['subway travel','food streets','seasonal celebrations']}}
};

export function resolveLanguageWorld(languageCode:string):LanguageWorld{const normalized=languageCode.toLowerCase().split('-')[0] as LanguageWorldId;return WORLDS[normalized]??WORLDS.ja;}
export function getLanguageWorlds():LanguageWorld[]{return Object.values(WORLDS);}
export const languageWorldEngine={resolve:resolveLanguageWorld,all:getLanguageWorlds};
