import { getLanguageWorldLocations } from '../../features/world/data/livingLanguageWorldLocations';

export type LanguageWorldId='ja'|'es'|'fr'|'ko';
export type WorldPlace={id:string;name:string;city:string;country:string;realWorldLocation:string;purpose:string;landmarks:string[];hiddenGems:string[];};
export type LanguageWorld={id:LanguageWorldId;languageCode:string;languageName:string;worldName:string;regionLabel:string;visualIdentity:string;places:WorldPlace[];culture:{greetings:string[];food:string[];dailyLife:string[]};};

const WORLDS:Record<LanguageWorldId,LanguageWorld>={
 ja:{id:'ja',languageCode:'ja',languageName:'Japanese',worldName:'Japanese World',regionLabel:'Real places and fictional learning places across Japan',visualIdentity:'A living Japanese language world: dense modern streets, historic districts, gardens, markets, railways, crafts, food alleys and seasonal places.',places:[],culture:{greetings:['こんにちは','おはよう'],food:['お茶','おにぎり','屋台料理'],dailyLife:['commuting','shopping','seasonal festivals','neighborhood routines']}},
 es:{id:'es',languageCode:'es',languageName:'Spanish',worldName:'Spanish World',regionLabel:'Real Spanish-speaking places across different countries',visualIdentity:'No single generic Spanish world: Mediterranean streets, plazas, Mexico City neighborhoods, Andean cities, Caribbean coasts and Southern Cone urban life each feel different.',places:[
  {id:'seville',name:'Seville',city:'Seville',country:'Spain',realWorldLocation:'Seville, Andalusia',purpose:'social conversation, food, directions and everyday street life',landmarks:['Plaza de España','Triana','Santa Cruz'],hiddenGems:['Alameda de Hércules','Calle Betis','local neighborhood plazas']},
  {id:'barcelona',name:'Barcelona',city:'Barcelona',country:'Spain',realWorldLocation:'Barcelona, Catalonia',purpose:'urban conversation, travel, shopping and city navigation',landmarks:['Sagrada Família','Gothic Quarter','La Boqueria'],hiddenGems:['Gràcia','Poblenou','quiet modernist streets']},
  {id:'mexico-city',name:'Mexico City',city:'Mexico City',country:'Mexico',realWorldLocation:'Mexico City',purpose:'real Mexican Spanish, markets, transport and rich everyday conversation',landmarks:['Centro Histórico','Chapultepec','Coyoacán'],hiddenGems:['Roma Sur','San Ángel','neighborhood mercados']},
  {id:'medellin',name:'Medellín',city:'Medellín',country:'Colombia',realWorldLocation:'Medellín, Antioquia',purpose:'Colombian Spanish, transport, social interaction and modern city life',landmarks:['Plaza Botero','Comuna 13','Metro Cable'],hiddenGems:['Laureles','Envigado','local cafés and parks']},
  {id:'buenos-aires',name:'Buenos Aires',city:'Buenos Aires',country:'Argentina',realWorldLocation:'Buenos Aires',purpose:'Rioplatense Spanish, cafés, conversation, culture and everyday life',landmarks:['San Telmo','La Boca','Recoleta'],hiddenGems:['Villa Crespo','Chacarita','traditional cafés']}
 ],culture:{greetings:['hola','buenos días'],food:['pan','café','regional street food'],dailyLife:['markets','family meals','city festivals','neighborhood social life']}},
 fr:{id:'fr',languageCode:'fr',languageName:'French',worldName:'French World',regionLabel:'Real French places and fictional learning places across France',visualIdentity:'A living French language world: historic streets, river cities, markets, cafés, bakeries, coastal towns, railways and regional architecture.',places:[],culture:{greetings:['bonjour','bonsoir'],food:['pain','fromage','pâtisserie'],dailyLife:['cafés','markets','riverside evenings','regional traditions']}},
 ko:{id:'ko',languageCode:'ko',languageName:'Korean',worldName:'Korean World',regionLabel:'Real Korean cities and regions',visualIdentity:'Seoul neighborhoods, Busan coastline, historic cities, food streets, mountains, subways and modern night scenes with distinct regional identities.',places:[
  {id:'seoul-ikseondong',name:'Ikseon-dong & Seoul',city:'Seoul',country:'South Korea',realWorldLocation:'Ikseon-dong and central Seoul',purpose:'everyday Korean, cafés, shopping, subway navigation and social life',landmarks:['Ikseon-dong Hanok Village','Gyeongbokgung area','Seoul subway'],hiddenGems:['Seochon','Mangwon','Euljiro alleys']},
  {id:'busan',name:'Busan',city:'Busan',country:'South Korea',realWorldLocation:'Busan',purpose:'coastal life, food ordering, travel and casual conversation',landmarks:['Gamcheon Culture Village','Jagalchi Market','Haeundae'],hiddenGems:['Huinnyeoul','Jeonpo Café Street','Yeongdo']},
  {id:'jeonju',name:'Jeonju',city:'Jeonju',country:'South Korea',realWorldLocation:'Jeonju, North Jeolla',purpose:'food, heritage vocabulary, polite interaction and cultural life',landmarks:['Jeonju Hanok Village','Gyeonggijeon','Nambu Market'],hiddenGems:['quiet hanok lanes','local bibimbap streets','traditional workshops']},
  {id:'gangneung',name:'Gangneung',city:'Gangneung',country:'South Korea',realWorldLocation:'Gangneung, Gangwon',purpose:'nature, coastal travel, cafés and seasonal language',landmarks:['Gyeongpo Beach','Anmok Coffee Street','Ojukheon'],hiddenGems:['quiet beaches','pine forests','small local cafés']}
 ],culture:{greetings:['안녕하세요','좋은 아침'],food:['김밥','차','street food'],dailyLife:['subway travel','food streets','seasonal celebrations','neighborhood cafés']}}
};

function canonicalPlaces(worldId:'japanese'|'french'):WorldPlace[]{return getLanguageWorldLocations(worldId).map(location=>({id:location.id,name:location.name,city:location.city??location.country,country:location.country,realWorldLocation:[location.city,location.country].filter(Boolean).join(', '),purpose:location.description,landmarks:location.kind==='real'?['Real-world location']:['Fictional learning location'],hiddenGems:location.experiences.includes('quest')?['Contextual learning encounter']:[]}));}
function materializeWorld(world:LanguageWorld):LanguageWorld{if(world.id==='ja')return{...world,worldName:'Japanese World',places:canonicalPlaces('japanese')};if(world.id==='fr')return{...world,worldName:'French World',places:canonicalPlaces('french')};return world;}
export function resolveLanguageWorld(languageCode:string):LanguageWorld{const normalized=languageCode.toLowerCase().split('-')[0] as LanguageWorldId;return materializeWorld(WORLDS[normalized]??WORLDS.ja);}
export function getLanguageWorlds():LanguageWorld[]{return (Object.values(WORLDS) as LanguageWorld[]).map(materializeWorld);}
export const languageWorldEngine={resolve:resolveLanguageWorld,all:getLanguageWorlds};
