import type { ResidentContextReaction } from './residentContextReactionEngine';
import type { ResidentRoutineState } from './residentRoutineEngine';
export type ResidentPresentationState={residentId:string;name:string;expression:'neutral'|'curious'|'warm'|'thinking'|'happy'|'encouraging';motion:'idle'|'breathing'|'listening'|'gesturing'|'thinking'|'working'|'greeting'|'goodbye';activity:'idle'|'walking'|'working'|'talking'|'observing';energy:number;shouldLookAtLearner:boolean;animationKey:string};
const expression=(value:ResidentContextReaction['expression']):ResidentPresentationState['expression']=>value==='friendly'?'warm':value==='pleased'?'happy':value==='concerned'?'encouraging':value;
const motion=(value:ResidentContextReaction['motion']|ResidentRoutineState['motion']):ResidentPresentationState['motion']=>value==='warm'?'breathing':value==='surprised'?'gesturing':value==='speaking'?'listening':value;
const activity=(value:ResidentRoutineState['activity']):ResidentPresentationState['activity']=>value==='resting'?'idle':value;
export function createResidentPresentation(residentId:string,name:string,routine:ResidentRoutineState,reaction?:ResidentContextReaction|null):ResidentPresentationState{const nextMotion=motion(reaction?.motion??routine.motion);const nextExpression=expression(reaction?.expression??'neutral');return{residentId,name,expression:nextExpression,motion:nextMotion,activity:activity(routine.activity),energy:routine.energy,shouldLookAtLearner:true,animationKey:`${residentId}:${nextMotion}:${nextExpression}`};}
export function updateResidentPresentation(current:ResidentPresentationState,reaction:ResidentContextReaction):ResidentPresentationState{const nextMotion=motion(reaction.motion);const nextExpression=expression(reaction.expression);return{...current,expression:nextExpression,motion:nextMotion,shouldLookAtLearner:true,animationKey:`${current.residentId}:${nextMotion}:${nextExpression}`};}
export const residentPresentationEngine={create:createResidentPresentation,update:updateResidentPresentation};
