import AsyncStorage from '@react-native-async-storage/async-storage';
import { eventBus } from '../events/eventBus';
import type { LivingEnvironment } from '../../features/world/components/LivingEnvironmentLayer';
import { worldStateEngine } from './worldStateEngine';

export type WorldOpportunity={id:string;title:string;detail:string;icon:string;locationKey:string;kind:'resident'|'weather'|'discovery'|'cassidy';choices:{id:string;label:string;detail:string;scenario?:string}[];createdAt:string;resolved?:boolean};
type Stored={active:WorldOpportunity[];lastGeneratedAt:string};
const DEFAULT_USER='local-explorer-user';
const keyFor=(userId:string)=>`gopal:living-world:opportunities:v2:${encodeURIComponent(userId)}`;
const catalog=(env:LivingEnvironment):WorldOpportunity[]=>[
{id:'ren-unusual-guest',title:'An unusual guest',detail:'Ren keeps glancing toward someone sitting alone by the café window.',icon:'☕',locationKey:'cozy_cafe',kind:'resident',choices:[{id:'listen',label:'Sit nearby',detail:'Stay close enough to hear what the evening is trying to say.',scenario:'scen-cafe-order'},{id:'ask',label:'Ask Ren later',detail:'Wait until the rush settles and ask what happened.'},{id:'leave',label:'Let it be',detail:'Some stories are not yours yet.'}],createdAt:new Date().toISOString()},
{id:'emi-old-page',title:'A page out of place',detail:'Emi has found something folded inside a book that should have been empty.',icon:'📚',locationKey:'whispering_library',kind:'discovery',choices:[{id:'investigate',label:'Investigate',detail:'Follow the clue and see where it points.',scenario:'scen-library-inquiry'},{id:'remember',label:'Ask Emi to keep it',detail:'Leave the mystery for another day.'}],createdAt:new Date().toISOString()},
{id:'kenji-lantern',title:'One lantern left',detail:'Kenji has a lantern that does not seem to belong to any stall.',icon:'🏮',locationKey:'lantern_market',kind:'resident',choices:[{id:'help',label:'Help hang it',detail:'Stay until the market becomes a little brighter.',scenario:'scen-market-browse'},{id:'ask',label:'Ask where it came from',detail:'Kenji smiles like the answer might take a while.'}],createdAt:new Date().toISOString()},
{id:'cassidy-night-call',title:'Cassidy wants to show you something',detail:'Cassidy has been waiting for nightfall. She says the valley looks different from one particular place.',icon:'✦',locationKey:'zen_garden',kind:'cassidy',choices:[{id:'follow',label:'Follow Cassidy',detail:'Go and see what she noticed.'},{id:'later',label:'Not tonight',detail:'Tell her you will come back when you are ready.'}],createdAt:new Date().toISOString()},
{id:'rain-market-shelter',title:'Rain gathers at the market',detail:'A sudden shower is sending people beneath the lantern awnings.',icon:'🌧',locationKey:'lantern_market',kind:'weather',choices:[{id:'join',label:'Join the crowd',detail:'Find out what people talk about while they wait for rain to pass.',scenario:'scen-market-browse'},{id:'wander',label:'Keep walking',detail:'The wet paths lead somewhere quieter.'}],createdAt:new Date().toISOString()},
{id:'ren-followup',title:'Ren remembers you',detail:'Ren notices you before you reach the counter. The unfinished conversation from before seems to have stayed with him.',icon:'☕',locationKey:'cozy_cafe',kind:'resident',choices:[{id:'continue',label:'Continue the conversation',detail:'Pick up where the earlier moment left off.',scenario:'scen-cafe-order'},{id:'smile',label:'Just stay a while',detail:'Not every return needs a destination.'}],createdAt:new Date().toISOString()},
{id:'kenji-followup',title:'A brighter market',detail:'The lantern you helped with is glowing above the market. Kenji points it out when he sees you.',icon:'🏮',locationKey:'lantern_market',kind:'resident',choices:[{id:'notice',label:'Look up',detail:'See what changed because you stayed.'},{id:'wander',label:'Keep moving',detail:'The gesture can still matter without becoming a task.'}],createdAt:new Date().toISOString()},
].filter(item=>env.weather==='rain'?item.kind==='weather'||item.kind==='resident':env.time==='night'?item.kind==='cassidy'||item.kind==='resident':item.kind!=='weather');

export class WorldOpportunityEngine{
 async load(environment:LivingEnvironment,continuityMinutes=0,userId=DEFAULT_USER):Promise<WorldOpportunity[]>{const key=keyFor(userId);const raw=await AsyncStorage.getItem(key);const stored:Stored=raw?JSON.parse(raw):{active:[],lastGeneratedAt:''};const existing=stored.active.filter(item=>!item.resolved);if(existing.length&&continuityMinutes<45)return existing;const flags=await worldStateEngine.all(userId);const options=catalog(environment).filter(item=>{if(item.id==='ren-followup')return Boolean(flags['resident:ren:approached']);if(item.id==='kenji-followup')return flags['opportunity:kenji-lantern:help']?.value===true;return !flags[`opportunity:${item.id}:closed`];});const followUps=options.filter(item=>item.id.endsWith('followup'));const pool=followUps.length?followUps:options;const count=continuityMinutes>180?2:1;const pick=pool.sort((a,b)=>a.id.localeCompare(b.id)).slice(0,count).map((item,index)=>({...item,id:`${item.id}:${Math.floor(Date.now()/600000)}:${index}`}));await AsyncStorage.setItem(key,JSON.stringify({active:pick,lastGeneratedAt:new Date().toISOString()}));pick.forEach(item=>eventBus.emit('world:eventStarted',{eventId:item.id,worldId:'emerald-valley'},'world'));return pick;}
 async resolve(opportunity:WorldOpportunity,choiceId:string,userId=DEFAULT_USER):Promise<void>{const key=keyFor(userId);const raw=await AsyncStorage.getItem(key);const stored:Stored=raw?JSON.parse(raw):{active:[],lastGeneratedAt:''};stored.active=stored.active.map(item=>item.id===opportunity.id?{...item,resolved:true}:item);await AsyncStorage.setItem(key,JSON.stringify(stored));const base=opportunity.id.split(':')[0];await worldStateEngine.mark(userId,`opportunity:${base}:closed`);await worldStateEngine.set(userId,`opportunity:${base}:${choiceId}`,true);if(base.startsWith('ren-unusual-guest'))await worldStateEngine.mark(userId,'resident:ren:approached');if(base.startsWith('emi-old-page')&&choiceId==='investigate')await worldStateEngine.mark(userId,'discovery:emi-old-page:investigated');eventBus.emit('world:eventResolved',{eventId:opportunity.id,choiceId,userId},'world');}
}
export const worldOpportunityEngine=new WorldOpportunityEngine();
