import { createResidentRoutineState, advanceResidentRoutine, noticeLearner, type ResidentRoutineState } from './residentRoutineEngine';
import { buildResidentContextReaction, type ResidentContextReaction } from './residentContextReactionEngine';
import { chooseOfflineWorldEvent, type WorldEvent } from './contextualWorldEventEngine';
import { startScenario, advanceArrival, submitLearnerTurn, completeScenario, advanceDeparture, type ScenarioExperienceState, type ScenarioOutcome, type LearnerTurnMode } from './worldScenarioExperienceEngine';
import { loadPersistentWorldState, recordVisit, recordWorldEvent, savePersistentWorldState, setRelationship, type PersistentWorldState } from './persistentWorldStateEngine';
import { createResidentRelationshipState, applyRelationshipOutcome } from './residentRelationshipMemoryEngine';
export type WorldExperiencePresentation={phase:'arrival'|'interaction'|'departure'|'world';camera:'establishing'|'face-to-face'|'departure-follow'|'world';cameraMode:'establishing'|'face-to-face'|'departure-follow'|'world';residentVisible:boolean;residentMotion:'idle'|'warm'|'gesturing'|'thinking'|'working';input:'hidden'|'typing-and-speaking';event:WorldEvent|null;reaction:ResidentContextReaction|null};
export type WorldExperienceDirectorState={scenario:ScenarioExperienceState;world:PersistentWorldState;routine:ResidentRoutineState;presentation:WorldExperiencePresentation};
function makePresentation(phase:WorldExperiencePresentation['phase'],routine:ResidentRoutineState,event:WorldEvent|null,reaction:ResidentContextReaction|null):WorldExperiencePresentation{const camera=phase==='arrival'?'establishing':phase==='interaction'?'face-to-face':phase==='departure'?'departure-follow':'world';return{phase,camera,cameraMode:camera,residentVisible:phase==='interaction'||phase==='departure',residentMotion:phase==='interaction'?(reaction?.motion??'warm'):routine.motion,input:phase==='interaction'?'typing-and-speaking':'hidden',event,reaction};}
export async function createWorldExperience(worldId:any,placeId:string,residentId:string,date=new Date()):Promise<WorldExperienceDirectorState>{const world=recordVisit(await loadPersistentWorldState(),placeId,residentId,date);const routine=noticeLearner(createResidentRoutineState(residentId,date));const scenario=startScenario(worldId,placeId,residentId,date);const reaction=buildResidentContextReaction(world.relationships[residentId]??createResidentRelationshipState(residentId),routine,scenario.runtime.snapshot);await savePersistentWorldState(world);return{world,scenario,routine,presentation:makePresentation('arrival',routine,null,reaction)};}
export function advanceWorldExperience(state:WorldExperienceDirectorState,elapsedMs:number):WorldExperienceDirectorState{if(state.scenario.phase==='arrival'){const scenario=advanceArrival(state.scenario,elapsedMs);return{...state,scenario,presentation:makePresentation(scenario.phase==='encounter'?'interaction':'arrival',state.routine,null,state.presentation.reaction)};}if(state.scenario.phase==='departure'){const scenario=advanceDeparture(state.scenario,elapsedMs);const routine=advanceResidentRoutine(state.routine);return{...state,scenario,routine,presentation:makePresentation(scenario.phase==='world'?'world':'departure',routine,state.presentation.event,state.presentation.reaction)};}return{...state,routine:advanceResidentRoutine(state.routine)};}
export function submitWorldLearnerTurn(state:WorldExperienceDirectorState,input:LearnerTurnMode,outcome:'success'|'confusion'):WorldExperienceDirectorState{const scenario=submitLearnerTurn(state.scenario,input,outcome);if(scenario===state.scenario)return state;const residentId=scenario.runtime.resident.residentId;const reaction=buildResidentContextReaction(state.world.relationships[residentId]??createResidentRelationshipState(residentId),state.routine,scenario.runtime.snapshot);return{...state,scenario,presentation:makePresentation('interaction',state.routine,state.presentation.event,reaction)};}
export async function finishWorldExperience(state:WorldExperienceDirectorState,outcome:ScenarioOutcome='completed'):Promise<WorldExperienceDirectorState>{const scenario=completeScenario(state.scenario,outcome);const residentId=scenario.runtime.resident.residentId;const relationship=applyRelationshipOutcome(state.world.relationships[residentId]??createResidentRelationshipState(residentId),outcome==='success'?'success':outcome==='confusion'?'difficulty':'goodbye',`Scenario completed with outcome: ${outcome}`);let world=setRelationship(state.world,relationship);if(state.presentation.event)world=recordWorldEvent(world,state.presentation.event,scenario.runtime.scene.placeId);await savePersistentWorldState(world);return{...state,world,scenario,presentation:makePresentation('departure',state.routine,state.presentation.event,state.presentation.reaction)};}
export function selectWorldMoment(state:WorldExperienceDirectorState):WorldExperienceDirectorState{const event=chooseOfflineWorldEvent({snapshot:state.scenario.runtime.snapshot,routine:state.routine,learnerSuccesses:state.scenario.outcome==='success'?1:0,learnerConfusions:state.scenario.outcome==='confusion'?1:0,minutesInScene:Math.floor(state.scenario.arrivalElapsedMs/60000)});return{...state,presentation:{...state.presentation,event}};}
export const worldExperienceDirector={create:createWorldExperience,advance:advanceWorldExperience,submit:submitWorldLearnerTurn,finish:finishWorldExperience,selectMoment:selectWorldMoment};
