import type { WorldMiniGameDefinition,WorldMiniGameKind,WorldMiniGameDifficulty,WorldMiniGameFamily,WorldMiniGameSkill } from './worldMiniGameEngine';

export type WorldMiniGameCatalogEntry=Pick<WorldMiniGameDefinition,'id'|'title'|'kind'|'family'|'difficulty'|'description'|'skills'|'estimatedMinutes'|'residentRequired'|'repeatable'|'tags'|'repeatCooldown'>;

const entry=(id:WorldMiniGameKind,title:string,family:WorldMiniGameFamily,difficulty:WorldMiniGameDifficulty,skills:WorldMiniGameSkill[],description:string,tags:string[],minutes=4,cooldown=8):WorldMiniGameCatalogEntry=>({id,title,kind:id,family,difficulty,skills,description,tags,estimatedMinutes:minutes,residentRequired:false,repeatable:true,repeatCooldown:cooldown});

export const WORLD_MINI_GAME_CATALOG:WorldMiniGameCatalogEntry[]=[
entry('word-hunt','Word Hunt','discovery','gentle',['vocabulary','reading','recall'],'Find useful target-language words hidden in a living scene.',['search','timed']),
entry('object-snap','Object Snap','discovery','playful',['vocabulary','recall'],'Identify moving objects and snap their correct words into place.',['objects','reflex']),
entry('sign-spotter','Sign Spotter','discovery','gentle',['reading','vocabulary'],'Read signs and infer their meaning from the surrounding place.',['signs','exploration']),
entry('hidden-phrase','Hidden Phrase','discovery','clever',['reading','vocabulary'],'Find scattered phrase fragments and reconstruct the message.',['search','phrases']),
entry('culture-clue-hunt','Culture Clue Hunt','discovery','clever',['culture','reading'],'Investigate cultural objects to uncover language clues.',['culture','investigation'],5),
entry('memory-trail','Memory Trail','discovery','playful',['vocabulary','memory','recall'],'Remember where words appeared and retrace the sequence.',['memory','map']),
entry('lost-label','Lost Label','discovery','gentle',['vocabulary','reading'],'Restore missing labels around a physical location.',['objects','repair']),
entry('sound-scout','Sound Scout','discovery','clever',['listening','recall'],'Locate the source of a spoken clue in the environment.',['audio','search']),
entry('phrase-builder','Phrase Builder','puzzle','playful',['grammar','reading','conversation'],'Assemble language pieces into a natural phrase.',['builder','grammar']),
entry('grammar-garden','Grammar Garden','puzzle','playful',['grammar','reading','recall'],'Repair language to make a magical garden grow.',['garden','world-change']),
entry('sentence-machine','Sentence Machine','puzzle','clever',['grammar','writing'],'Feed words into a machine in natural grammatical order.',['logic','grammar']),
entry('particle-puzzle','Particle Puzzle','puzzle','clever',['grammar'],'Place the particle that makes each sentence natural.',['grammar','precision']),
entry('verb-workshop','Verb Workshop','puzzle','playful',['grammar','verbs'],'Transform verbs to fit time, intent and situation.',['verbs','craft'],5),
entry('word-forge','Word Forge','puzzle','playful',['vocabulary','word-building'],'Forge valid words from language pieces.',['word-building','craft']),
entry('kanji-tile-forge','Kanji Tile Forge','puzzle','clever',['kanji','reading'],'Assemble and read kanji compounds from tiles.',['kanji','tiles'],5),
entry('translation-tangle','Translation Tangle','puzzle','playful',['translation','reading'],'Untangle a mixed translation and restore its intended meaning.',['translation','logic']),
entry('context-lock','Context Lock','puzzle','clever',['reading','grammar'],'Use contextual language clues to unlock a fictional place.',['mystery','context'],5),
entry('logic-lanterns','Logic Lanterns','puzzle','clever',['grammar','reading'],'Light lanterns in the correct language sequence.',['logic','mystery'],5),
entry('speed-round','Speed Round','arcade','wild',['vocabulary','grammar','listening','recall'],'Rapid escalating language decisions.',['arcade','speed'],2,10),
entry('falling-words','Falling Words','arcade','wild',['vocabulary'],'Catch correct words while avoiding distractors.',['arcade','reflex'],3,10),
entry('word-dash','Word Dash','arcade','wild',['vocabulary','reading'],'Choose the correct lane while language clues race toward you.',['movement','speed'],3,10),
entry('listening-chase','Listening Chase','arcade','playful',['listening','vocabulary','recall'],'Follow audio clues through a location.',['audio','exploration']),
entry('quick-reply','Quick Reply','arcade','wild',['speaking','conversation'],'Choose the natural reply before the moment passes.',['social','speed'],3,10),
entry('flash-recall','Flash Recall','arcade','wild',['vocabulary','memory'],'Rapidly recall meaning from changing visual cues.',['recall','speed'],2,10),
entry('match-rush','Match Rush','arcade','playful',['vocabulary','recall'],'Pair words, meanings, sounds and objects under pressure.',['matching','timed']),
entry('sound-catcher','Sound Catcher','arcade','playful',['listening','vocabulary'],'Catch the spoken word matching the target.',['audio','reflex']),
entry('grammar-dodge','Grammar Dodge','arcade','wild',['grammar'],'Dodge incorrect sentence obstacles.',['grammar','arcade'],3,10),
entry('vocabulary-meteor','Vocabulary Meteor','arcade','wild',['vocabulary','recall'],'Defend a location by choosing correct meanings as meteors fall.',['arcade','action'],3,10),
entry('politeness-duel','Politeness Duel','social','clever',['conversation','culture','speaking'],'Choose socially appropriate language for changing situations.',['social','culture']),
entry('dialogue-detective','Dialogue Detective','social','clever',['reading','listening','conversation','culture'],'Infer what people mean from dialogue and context.',['mystery','dialogue'],5),
entry('market-rush','Market Rush','social','wild',['listening','vocabulary','conversation','culture'],'Handle changing requests and reactions at a busy market.',['market','arcade'],5,10),
entry('cafe-order','Café Order','social','playful',['listening','speaking','vocabulary'],'Listen, remember and place a correct café order.',['cafe','memory']),
entry('train-counter','Train Counter','social','clever',['speaking','reading','navigation'],'Buy the correct ticket using travel clues.',['travel','roleplay'],5),
entry('neighbor-favor','Neighbor Favor','social','playful',['listening','speaking','conversation'],'Understand a friendly request and respond naturally.',['community','social']),
entry('lost-tourist','Lost Tourist','social','playful',['speaking','navigation','listening'],'Give or understand directions through a real location.',['navigation','help'],5),
entry('message-relay','Message Relay','social','wild',['listening','memory','conversation'],'Remember and accurately pass a spoken message.',['memory','audio'],4,10),
entry('emotion-reader','Emotion Reader','social','clever',['speaking','culture','conversation'],'Match tone and emotion with an appropriate response.',['emotion','social']),
entry('conversation-repair','Conversation Repair','social','playful',['speaking','grammar','conversation'],'Repair awkward dialogue with a natural language choice.',['dialogue','repair']),
entry('echo-station','Echo Station','listening','gentle',['listening','recall'],'Identify repeated target-language sounds and phrases.',['audio','recall']),
entry('audio-map','Audio Map','listening','clever',['listening','navigation'],'Follow spoken directions across a map.',['audio','navigation'],5),
entry('voice-match','Voice Match','listening','gentle',['listening','conversation'],'Match a spoken phrase to the correct situation.',['audio','context']),
entry('missing-word-radio','Missing Word Radio','listening','playful',['listening','vocabulary'],'Fill missing words in short broadcasts.',['audio','fill']),
entry('street-noise','Street Noise','listening','clever',['listening','recall'],'Separate useful language from harmless ambient sound.',['audio','attention']),
entry('rhythm-repeat','Rhythm Repeat','listening','playful',['listening','speaking'],'Choose the phrase matching speech rhythm and intent.',['audio','rhythm']),
entry('announcement-alert','Announcement Alert','listening','wild',['listening','reading'],'Understand a public announcement quickly.',['audio','travel','speed'],3,10),
entry('whisper-trail','Whisper Trail','listening','clever',['listening','reading'],'Follow quiet clues through a hidden location.',['mystery','audio'],5),
entry('mystery-room','Mystery Room','adventure','wild',['grammar','vocabulary','reading','recall'],'Solve a chain of language puzzles in a strange room.',['puzzle','story','fictional'],7,12),
entry('story-choice','Story Choice','adventure','playful',['reading','speaking','culture','vocabulary'],'Shape a branching story through language choices.',['story','choices'],6,10),
entry('detective-case','Detective Case','adventure','clever',['reading','listening','vocabulary'],'Solve a small mystery from language clues.',['detective','mystery'],7,12),
entry('treasure-map','Treasure Map','adventure','playful',['reading','vocabulary','navigation'],'Decode clues to discover a hidden destination.',['map','adventure'],6),
entry('festival-prep','Festival Prep','adventure','playful',['mixed','culture','vocabulary'],'Prepare a festival using varied language tasks.',['festival','variety'],8,14),
entry('time-traveler','Time Traveler','adventure','wild',['reading','culture','vocabulary'],'Navigate fictional eras using language clues.',['time','adventure'],8,14),
entry('dream-theatre','Dream Theatre','adventure','clever',['speaking','creative','conversation'],'Act through surreal language scenes and choices.',['dream','story'],7,14),
entry('secret-agent','Secret Agent','adventure','wild',['reading','listening','recall'],'Decode harmless messages to identify the next objective.',['agent','decode'],6,12),
entry('escape-the-archive','Escape the Archive','adventure','wild',['grammar','reading','vocabulary'],'Solve language locks to escape a fictional archive.',['archive','puzzle'],8,12),
entry('lantern-mystery','Lantern Mystery','adventure','clever',['listening','reading','culture'],'Investigate a night-time fictional mystery.',['night','mystery'],7,12),
entry('sign-designer','Sign Designer','creative','clever',['writing','vocabulary'],'Construct a useful sign from language pieces.',['design','writing'],5),
entry('story-composer','Story Composer','creative','clever',['writing','reading'],'Arrange scenes and phrases into a coherent story.',['story','creative'],6),
entry('recipe-creator','Recipe Creator','creative','playful',['reading','vocabulary','writing'],'Sequence ingredients and instructions using target-language clues.',['food','sequence'],5),
entry('world-builder','World Builder','creative','clever',['mixed','writing','creative'],'Use correct language commands to construct a small scene.',['building','world'],7,12),
];

export const WORLD_MINI_GAME_COUNT=WORLD_MINI_GAME_CATALOG.length;
export const getWorldMiniGameCatalog=()=>WORLD_MINI_GAME_CATALOG.map(game=>({...game,skills:[...game.skills],tags:[...game.tags]}));
export const getWorldMiniGameById=(id:string)=>WORLD_MINI_GAME_CATALOG.find(game=>game.id===id)??null;
