import type {WorldMiniGameDefinition,WorldMiniGameFamily,WorldMiniGameKind}from'./worldMiniGameEngine';
import{WORLD_MINI_GAME_CATALOG}from'./worldMiniGameCatalog';

export type WorldMiniGameMechanic='target'|'sequence'|'memory'|'timed-choice'|'matching'|'social-choice'|'audio-navigation'|'investigation'|'story-choice'|'crafting'|'rhythm'|'construction';
export type WorldMiniGameRuntimeBinding={id:string;mechanic:WorldMiniGameMechanic;implemented:boolean;family:WorldMiniGameFamily;kind:WorldMiniGameKind;notes:string};

const binding=(id:string,mechanic:WorldMiniGameMechanic,notes:string):WorldMiniGameRuntimeBinding=>{const game=WORLD_MINI_GAME_CATALOG.find(item=>item.id===id);if(!game)throw new Error(`Unknown mini-game catalog id: ${id}`);return{id,mechanic,implemented:true,family:game.family,kind:game.kind,notes}};

export const WORLD_MINI_GAME_RUNTIME_REGISTRY:WorldMiniGameRuntimeBinding[]=[
 binding('word-hunt','target','Scene target selection'),binding('object-snap','target','Moving object targeting'),binding('sign-spotter','target','Contextual sign discovery'),binding('hidden-phrase','sequence','Phrase fragment ordering'),binding('culture-clue-hunt','investigation','Prerequisite clue chain'),binding('memory-trail','memory','Spatial recall'),binding('lost-label','target','Object label restoration'),binding('sound-scout','investigation','Audio source discovery'),
 binding('phrase-builder','sequence','Language piece ordering'),binding('grammar-garden','construction','Repair/build interaction'),binding('sentence-machine','sequence','Grammar sequence'),binding('particle-puzzle','sequence','Particle placement'),binding('verb-workshop','crafting','Language transformation recipe'),binding('word-forge','crafting','Word-piece construction'),binding('kanji-tile-forge','construction','Tile assembly'),binding('translation-tangle','sequence','Meaning reconstruction'),binding('context-lock','investigation','Context unlock'),binding('logic-lanterns','sequence','Logical sequence'),
 binding('speed-round','timed-choice','Rapid decisions'),binding('falling-words','target','Timed falling targets'),binding('word-dash','target','Lane selection'),binding('listening-chase','audio-navigation','Audio-guided movement'),binding('quick-reply','timed-choice','Timed social response'),binding('flash-recall','memory','Rapid recall'),binding('match-rush','matching','Timed matching'),binding('sound-catcher','target','Audio target capture'),binding('grammar-dodge','target','Avoidance/action'),binding('vocabulary-meteor','target','Timed defensive targeting'),
 binding('politeness-duel','social-choice','Context-sensitive social choices'),binding('dialogue-detective','investigation','Dialogue evidence'),binding('market-rush','social-choice','Dynamic market interaction'),binding('cafe-order','memory','Order recall'),binding('train-counter','social-choice','Travel transaction'),binding('neighbor-favor','social-choice','Request/response'),binding('lost-tourist','audio-navigation','Direction giving/following'),binding('message-relay','memory','Message recall'),binding('emotion-reader','social-choice','Tone/context response'),binding('conversation-repair','social-choice','Dialogue repair'),
 binding('echo-station','memory','Audio recall'),binding('audio-map','audio-navigation','Spoken map navigation'),binding('voice-match','matching','Audio/context matching'),binding('missing-word-radio','timed-choice','Broadcast completion'),binding('street-noise','audio-navigation','Audio attention'),binding('rhythm-repeat','rhythm','Speech rhythm timing'),binding('announcement-alert','timed-choice','Timed announcement response'),binding('whisper-trail','audio-navigation','Quiet clue navigation'),
 binding('mystery-room','investigation','Multi-clue fictional room'),binding('story-choice','story-choice','Branching story'),binding('detective-case','investigation','Evidence chain'),binding('treasure-map','audio-navigation','Clue-driven map navigation'),binding('festival-prep','crafting','Multi-step festival preparation'),binding('time-traveler','story-choice','Branching fictional era'),binding('dream-theatre','story-choice','Surreal branching scene'),binding('secret-agent','sequence','Message decoding'),binding('escape-the-archive','investigation','Layered archive clues'),binding('lantern-mystery','investigation','Night mystery'),
 binding('sign-designer','construction','Sign construction'),binding('story-composer','sequence','Scene composition'),binding('recipe-creator','crafting','Recipe construction'),binding('world-builder','construction','Scene building'),
];

export const getRuntimeBinding=(id:string)=>WORLD_MINI_GAME_RUNTIME_REGISTRY.find(item=>item.id===id)??null;
export const getImplementedRuntimeGames=()=>WORLD_MINI_GAME_RUNTIME_REGISTRY.filter(item=>item.implemented);
export const getUnboundCatalogGames=()=>WORLD_MINI_GAME_CATALOG.filter(game=>!getRuntimeBinding(game.id));
export const getRuntimeCoverage=()=>({catalogCount:WORLD_MINI_GAME_CATALOG.length,boundCount:WORLD_MINI_GAME_RUNTIME_REGISTRY.length,unboundCount:getUnboundCatalogGames().length});
export type WorldMiniGameRuntimeDefinition=WorldMiniGameDefinition&{runtimeMechanic:WorldMiniGameMechanic};
export function resolveRuntimeDefinition(game:WorldMiniGameDefinition):WorldMiniGameRuntimeDefinition|null{const runtime=getRuntimeBinding(game.id);return runtime?{...game,runtimeMechanic:runtime.mechanic}:null}
