import type { WorldAudioLocationProfile } from './worldAudioContract';

export const WORLD_AUDIO_PROFILES: Record<string, WorldAudioLocationProfile> = {
  emeraldValley: {
    id: 'emeraldValley',
    displayName: 'Emerald Valley',
    environment: 'outdoor',
    music: ['emerald-valley-theme'],
    ambience: ['soft-wind', 'distant-birds', 'grass-movement'],
    location: ['distant-valley-roomtone'],
    activity: ['light-footsteps'],
    transport: [],
    interactions: ['soft-discovery-chime'],
    eventCues: ['wonder-moment'],
    defaultDensity: 0.42,
    maxActiveOneShots: 3,
    musicGain: 0.8,
    ambienceGain: 0.9,
    locationGain: 0.35,
    activityGain: 0.55,
    eventGain: 0.7,
    reverbPreset: 'open',
  },
  trainStation: {
    id: 'trainStation',
    displayName: 'Train Station',
    environment: 'covered',
    music: ['train-station-pulse'],
    ambience: ['station-air', 'soft-crowd-bed', 'platform-roomtone'],
    location: ['rail-hum', 'distant-platform-activity'],
    activity: ['footsteps-platform'],
    transport: ['train-pass-distant', 'train-arrival-soft'],
    interactions: ['station-door-soft'],
    eventCues: ['station-arrival', 'station-departure'],
    defaultDensity: 0.38,
    maxActiveOneShots: 4,
    musicGain: 0.72,
    ambienceGain: 0.62,
    locationGain: 0.52,
    activityGain: 0.38,
    eventGain: 0.64,
    reverbPreset: 'station',
  },
  cafe: {
    id: 'cafe',
    displayName: 'Café',
    environment: 'indoor',
    music: ['cafe-warm-theme'],
    ambience: ['soft-roomtone', 'muffled-conversation'],
    location: ['cups-and-room-texture'],
    activity: ['light-footsteps'],
    transport: [],
    interactions: ['cup-place-soft', 'door-soft'],
    eventCues: ['cafe-discovery'],
    defaultDensity: 0.32,
    maxActiveOneShots: 3,
    musicGain: 0.58,
    ambienceGain: 0.54,
    locationGain: 0.42,
    activityGain: 0.25,
    eventGain: 0.55,
    reverbPreset: 'cafe',
  },
  library: {
    id: 'library',
    displayName: 'Library',
    environment: 'indoor',
    music: ['library-air'],
    ambience: ['quiet-roomtone'],
    location: ['page-turns-distant', 'soft-building-hum'],
    activity: ['quiet-footsteps'],
    transport: [],
    interactions: ['book-place-soft'],
    eventCues: ['library-discovery'],
    defaultDensity: 0.16,
    maxActiveOneShots: 2,
    musicGain: 0.22,
    ambienceGain: 0.32,
    locationGain: 0.3,
    activityGain: 0.16,
    eventGain: 0.42,
    reverbPreset: 'large-room',
  },
  forest: {
    id: 'forest',
    displayName: 'Forest',
    environment: 'outdoor',
    music: ['forest-spacious-theme'],
    ambience: ['leaves-soft', 'forest-wind', 'distant-birds'],
    location: ['branch-creak-distant'],
    activity: ['forest-footsteps'],
    transport: [],
    interactions: ['nature-discovery-soft'],
    eventCues: ['forest-wonder'],
    defaultDensity: 0.36,
    maxActiveOneShots: 3,
    musicGain: 0.42,
    ambienceGain: 0.82,
    locationGain: 0.42,
    activityGain: 0.28,
    eventGain: 0.62,
    reverbPreset: 'forest',
  },
  airport: {
    id: 'airport',
    displayName: 'Airport',
    environment: 'covered',
    music: ['airport-travel-theme'],
    ambience: ['terminal-air', 'soft-travel-crowd'],
    location: ['luggage-roll-distant', 'muffled-terminal-announcement'],
    activity: ['terminal-footsteps'],
    transport: ['aircraft-distant', 'service-cart-distant'],
    interactions: ['terminal-door-soft'],
    eventCues: ['airport-arrival', 'airport-discovery'],
    defaultDensity: 0.3,
    maxActiveOneShots: 3,
    musicGain: 0.52,
    ambienceGain: 0.5,
    locationGain: 0.4,
    activityGain: 0.26,
    eventGain: 0.58,
    reverbPreset: 'large-room',
  },
  studyRoom: {
    id: 'studyRoom',
    displayName: 'Study Room',
    environment: 'indoor',
    music: ['study-focus-air'],
    ambience: ['quiet-roomtone'],
    location: ['clock-soft', 'paper-texture'],
    activity: ['pencil-soft', 'chair-shift-soft'],
    transport: [],
    interactions: ['page-turn-soft'],
    eventCues: ['focus-complete'],
    defaultDensity: 0.12,
    maxActiveOneShots: 2,
    musicGain: 0.2,
    ambienceGain: 0.28,
    locationGain: 0.26,
    activityGain: 0.18,
    eventGain: 0.45,
    reverbPreset: 'small-room',
  },
  nightStreet: {
    id: 'nightStreet',
    displayName: 'Night Streets',
    environment: 'outdoor',
    music: ['night-street-theme'],
    ambience: ['night-air', 'distant-insects'],
    location: ['soft-city-hum'],
    activity: ['night-footsteps'],
    transport: ['car-pass-distant'],
    interactions: ['street-door-soft'],
    eventCues: ['night-wonder'],
    defaultDensity: 0.24,
    maxActiveOneShots: 3,
    musicGain: 0.44,
    ambienceGain: 0.56,
    locationGain: 0.38,
    activityGain: 0.25,
    eventGain: 0.58,
    reverbPreset: 'open',
  },
  festival: {
    id: 'festival',
    displayName: 'Festival',
    environment: 'outdoor',
    music: ['festival-local-theme'],
    ambience: ['festival-air', 'soft-crowd-bed'],
    location: ['decorations-soft', 'distant-laughter'],
    activity: ['festival-footsteps'],
    transport: [],
    interactions: ['festival-interaction-soft'],
    eventCues: ['festival-moment'],
    defaultDensity: 0.34,
    maxActiveOneShots: 4,
    musicGain: 0.62,
    ambienceGain: 0.54,
    locationGain: 0.38,
    activityGain: 0.3,
    eventGain: 0.72,
    reverbPreset: 'open',
  },
};

export function getWorldAudioProfile(locationId: string): WorldAudioLocationProfile | undefined {
  return WORLD_AUDIO_PROFILES[locationId];
}
