import AsyncStorage from '@react-native-async-storage/async-storage';
import { LanguageWorldId, WorldPlace, languageWorldEngine, resolveLanguageWorld } from './languageWorldEngine';
import { getLanguageWorldLocations } from '../../features/world/data/livingLanguageWorldLocations';
export type WorldPresence=|{kind:'home';worldId:'emerald-valley';label:'Emerald Valley'}|{kind:'journey';worldId:LanguageWorldId;placeId:string;label:string};
const KEY='gopal:world-presence:v1';
const LEGACY_PLACE_IDS:Record<string,string>={'tokyo-komorebi-cafe':'jp-tokyo-cafe','kyoto-whispering-garden':'jp-kyoto-whispering-garden','osaka-lantern-market':'jp-osaka-night-market','kanazawa-craft-house':'jp-kanazawa-craft-house','fukuoka-yatai-alley':'jp-fukuoka-yatai-alley','paris-lune-bakery':'fr-paris-bakery','lyon-story-square':'fr-lyon-story-square','strasbourg-market-quarter':'fr-strasbourg-christmas-quarter','nice-promenade-studio':'fr-nice-promenade-studio','tokyo-shibuya':'jp-tokyo-shibuya','kyoto-gion':'jp-kyoto-gion','osaka-dotonbori':'jp-osaka-dotonbori','kanazawa':'jp-kanazawa','fukuoka-hakata':'jp-fukuoka-hakata','paris-montmartre':'fr-paris-montmartre','lyon':'fr-lyon-old-town','strasbourg':'fr-strasbourg','nice':'fr-nice'};
function canonicalPlaceId(placeId:string){return LEGACY_PLACE_IDS[placeId]??placeId;}
function canonicalWorldId(worldId:LanguageWorldId){return worldId;}
function journey(worldId:LanguageWorldId,place:WorldPlace):WorldPresence{return{kind:'journey',worldId:canonicalWorldId(worldId),placeId:canonicalPlaceId(place.id),label:`${place.name}, ${place.city}`};}
export class WorldPresenceEngine{private currentPresence:WorldPresence={kind:'home',worldId:'emerald-valley',label:'Emerald Valley'};async hydrate():Promise<WorldPresence>{try{const raw=await AsyncStorage.getItem(KEY);if(!raw)return this.currentPresence;const parsed=JSON.parse(raw) as WorldPresence;if(parsed.kind==='journey'){const world=resolveLanguageWorld(parsed.worldId);const canonicalId=canonicalPlaceId(parsed.placeId);const place=world.places.find(item=>canonicalPlaceId(item.id)===canonicalId);if(place){this.currentPresence=journey(world.id,place);return this.currentPresence;}}this.currentPresence={kind:'home',worldId:'emerald-valley',label:'Emerald Valley'};}catch{this.currentPresence={kind:'home',worldId:'emerald-valley',label:'Emerald Valley'};}return this.currentPresence;}current():WorldPresence{return this.currentPresence;}async goHome():Promise<WorldPresence>{this.currentPresence={kind:'home',worldId:'emerald-valley',label:'Emerald Valley'};try{await AsyncStorage.setItem(KEY,JSON.stringify(this.currentPresence));}catch{}return this.currentPresence;}async travel(worldId:LanguageWorldId,placeId?:string):Promise<WorldPresence>{const world=languageWorldEngine.resolve(worldId);const canonicalId=canonicalPlaceId(placeId??'');const place=world.places.find(item=>canonicalPlaceId(item.id)===canonicalId)||world.places[0];if(!place)throw new Error(`No destinations configured for ${worldId}`);this.currentPresence=journey(world.id,place);try{await AsyncStorage.setItem(KEY,JSON.stringify(this.currentPresence));}catch{}return this.currentPresence;}destination():WorldPlace|null{if(this.currentPresence.kind!=='journey')return null;const worldId=this.currentPresence.worldId;const placeId=canonicalPlaceId(this.currentPresence.placeId);return resolveLanguageWorld(worldId).places.find(item=>canonicalPlaceId(item.id)===placeId)??null;}}
export const worldPresenceEngine=new WorldPresenceEngine();
