import React,{useEffect,useMemo,useRef}from'react';
import{Animated,Easing,Text,View}from'react-native';
import{useLivingResidents}from'./LivingResidentLayer';
import{propInteractionFor,WorldPropInteraction}from'../../../engines/world/worldPropInteractionEngine';
function TeaStation({pulse}:{pulse:Animated.Value}){const steam=pulse.interpolate({inputRange:[0,1],outputRange:[0,-10]});return <View className="items-center"><View className="h-3 w-8 rounded-full bg-amber-200/30"/><View className="-mt-1 h-5 w-6 rounded-b-lg rounded-t-sm border border-amber-100/40 bg-amber-100/20"/><Animated.View style={{transform:[{translateY:steam}],opacity:pulse}} className="absolute -top-4"><Text className="text-sm text-white/35">〰</Text></Animated.View></View>;}
function BookClue({pulse}:{pulse:Animated.Value}){const lift=pulse.interpolate({inputRange:[0,1],outputRange:[0,-3]});return <Animated.View style={{transform:[{translateY:lift}]}} className="items-center"><View className="h-2 w-7 rounded-t-sm bg-violet-100/40"/><View className="h-3 w-7 rounded-b-sm bg-slate-100/20"/><View className="absolute -top-2 h-1.5 w-1.5 rounded-full bg-violet-200/70"/></Animated.View>;}
function LanternHook({pulse}:{pulse:Animated.Value}){const swing=pulse.interpolate({inputRange:[0,1],outputRange:['-5deg','5deg']});return <Animated.View style={{transform:[{rotate:swing}]}} className="items-center"><View className="h-7 w-0.5 bg-amber-100/40"/><View className="h-6 w-5 rounded-b-lg border border-amber-100/60 bg-amber-300/45 shadow-lg shadow-amber-200"/></Animated.View>;}
function WaterRipple({pulse}:{pulse:Animated.Value}){const scale=pulse.interpolate({inputRange:[0,1],outputRange:[0.7,1.35]});return <Animated.View style={{transform:[{scale}],opacity:pulse.interpolate({inputRange:[0,1],outputRange:[0.75,0.15]})}} className="h-5 w-9 rounded-[50%] border border-cyan-200/45"/>;}
function PropVisual({interaction,pulse}:{interaction:WorldPropInteraction;pulse:Animated.Value}){if(interaction.kind==='tea_station')return <TeaStation pulse={pulse}/>;if(interaction.kind==='book_clue')return <BookClue pulse={pulse}/>;if(interaction.kind==='lantern_hook')return <LanternHook pulse={pulse}/>;return <WaterRipple pulse={pulse}/>;}
export function LivingPropInteractionLayer({timeOffsetMinutes=0}:{timeOffsetMinutes?:number}){const residents=useLivingResidents(timeOffsetMinutes);const pulse=useRef(new Animated.Value(0)).current;useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:1500,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:1500,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));loop.start();return()=>loop.stop();},[pulse]);const interactions=useMemo(()=>residents.map(r=>propInteractionFor(r.id,r.activity,r.locationKey)).filter((x):x is WorldPropInteraction=>Boolean(x)),[residents]);return <View pointerEvents="none" className="absolute inset-0 z-[29]">{interactions.map(item=><View key={`${item.residentId}:${item.kind}`} style={{position:'absolute',left:`${item.x}%`,top:`${item.y}%`}}><PropVisual interaction={item} pulse={pulse}/></View>)}</View>;}
