import { useEffect, useState, useCallback } from 'react';
import { CharacterEngine } from '../engines/character/characterEngine';
import type { CassidyView } from '../engines/character/characterEngine';
import { tutorEngine } from '../engines/tutor/tutorEngine';
import { auth } from '../services/auth';
import type { Mood } from '../lib/types';
import { loadCassidySnapshot, type CassidySnapshot } from '../characters/cassidyContext';
import { eventBus } from '../engines/events/eventBus';
import { processCassidyInteraction } from '../engines/cassidy/cassidyInteractionLifecycleEngine';

const characterEngine = new CharacterEngine();

function createMessageId(kind:'user'|'cassidy'){return `msg-${kind}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
function createInteractionId(userId:string){return `cassidy-chat:${userId}:${Date.now()}:${Math.random().toString(36).slice(2,10)}`;}
function contextForCassidy(snapshot:CassidySnapshot|null){if(!snapshot)return '';const recentSignals=[snapshot.echoes>0?`${snapshot.echoes} learning echoes`:null,snapshot.worldEchoes>0?`${snapshot.worldEchoes} world echoes`:null,snapshot.souvenirs>0?`${snapshot.souvenirs} souvenirs`:null,snapshot.threads>0?`${snapshot.threads} memory threads`:null,snapshot.decisions>0?`${snapshot.decisions} remembered decisions`:null].filter(Boolean).join(', ');return ['Cassidy context (use only as background; never claim details not present here):',recentSignals?`The learner has ${recentSignals}.`:'The learner has not built a recorded history yet.',snapshot.lastMode?`Their last recorded mode was ${snapshot.lastMode}.`:null,`The living world currently has bonsai growth ${snapshot.bonsaiGrowth} and radio growth ${snapshot.radioGrowth}.`].filter(Boolean).join(' ');}
export interface CassidyChatMessage{id:string;sender:'user'|'cassidy';text:string;timestamp:string;}
export function useCassidy(){const[view,setView]=useState<CassidyView|null>(null);const[snapshot,setSnapshot]=useState<CassidySnapshot|null>(null);const[userId,setUserId]=useState('local-explorer-user');const[messages,setMessages]=useState<CassidyChatMessage[]>([{id:'init-1',sender:'cassidy',text:'“Welcome back to our world! What shall we discover or practice together today?”',timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}]);
const reload=useCallback(async(uid:string)=>{const[loaded,worldSnapshot]=await Promise.all([characterEngine.loadCassidy(uid),loadCassidySnapshot()]);setView(loaded);setSnapshot(worldSnapshot);},[]);
useEffect(()=>{let active=true;const unsub=auth.onAuthStateChange(async user=>{const uid=user?user.id:'local-explorer-user';setUserId(uid);const[loaded,worldSnapshot]=await Promise.all([characterEngine.loadCassidy(uid),loadCassidySnapshot()]);if(active){setView(loaded);setSnapshot(worldSnapshot);}});const refreshOnWorldChange=()=>{void reload(userId);};const eventSubscriptions=[eventBus.on('learning:sessionCompleted',refreshOnWorldChange),eventBus.on('discovery:made',refreshOnWorldChange),eventBus.on('quest:completed',refreshOnWorldChange),eventBus.on('story:progressed',refreshOnWorldChange),eventBus.on('achievement:earned',refreshOnWorldChange),eventBus.on('location:unlocked',refreshOnWorldChange),eventBus.on('world:locationChanged',refreshOnWorldChange),eventBus.on('conversation:completed',refreshOnWorldChange),eventBus.on('world:eventStarted',refreshOnWorldChange),eventBus.on('world:returned',refreshOnWorldChange),eventBus.on('world:residentEncountered',refreshOnWorldChange),eventBus.on('world:residentMoment',refreshOnWorldChange),eventBus.on('memory:recorded',refreshOnWorldChange)];return()=>{active=false;unsub.data.subscription.unsubscribe();eventSubscriptions.forEach(unsubscribe=>unsubscribe());};},[reload,userId]);
const sendMessage=useCallback(async(text:string)=>{const trimmed=text.trim();if(!trimmed)return;const userMsg:CassidyChatMessage={id:createMessageId('user'),sender:'user',text:trimmed,timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};setMessages(prev=>[...prev,userMsg]);const mood=view?.state?.mood??'curious';const context=contextForCassidy(snapshot);const prompt=context?`${context}\n\nLearner says: ${trimmed}`:trimmed;const cassidyReply=tutorEngine.generateCassidyResponse(prompt,mood);const replyMsg:CassidyChatMessage={id:createMessageId('cassidy'),sender:'cassidy',text:cassidyReply,timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};setMessages(prev=>[...prev,replyMsg]);const interactionId=createInteractionId(userId);await processCassidyInteraction({userId,characterId:view?.character?.id??'char-cassidy',interactionId,outcome:'neutral',summary:`Cassidy conversation: ${trimmed}`,activity:'conversation'});await reload(userId);},[view,snapshot,userId,reload]);
const updateMood=useCallback(async(newMood:Mood)=>{if(!view?.character)return;await characterEngine.setMood(view.character.id,newMood,view.state?.energy??85,view.state?.current_activity??null);await reload(userId);},[view,userId,reload]);return{view,snapshot,characterEngine,messages,sendMessage,updateMood,refresh:()=>reload(userId)};}
