import React,{useEffect,useMemo,useRef,useState}from'react';
import{Animated,Easing,Pressable,StyleSheet,Text,View}from'react-native';
import{cassidyWelcomeEngine}from'../../../engines/cassidy/cassidyWelcomeEngine';
import{CassidyCharacter}from'../../../components/CassidyCharacter';

export function CassidyFirstMeetingCinematic({visible,onComplete}:{visible:boolean;onComplete:()=>void}){
 const[line,setLine]=useState(0);const fade=useRef(new Animated.Value(0)).current;const rise=useRef(new Animated.Value(34)).current;const veil=useRef(new Animated.Value(1)).current;const orb=useRef(new Animated.Value(0)).current;const stars=useRef(new Animated.Value(0)).current;const script=useMemo(()=>cassidyWelcomeEngine.script,[]);
 useEffect(()=>{if(!visible)return;setLine(0);fade.setValue(0);rise.setValue(34);veil.setValue(1);orb.setValue(0);stars.setValue(0);const float=Animated.loop(Animated.sequence([Animated.timing(orb,{toValue:1,duration:3200,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(orb,{toValue:0,duration:3200,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));const shimmer=Animated.loop(Animated.sequence([Animated.timing(stars,{toValue:1,duration:2400,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(stars,{toValue:0,duration:2400,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));float.start();shimmer.start();Animated.parallel([Animated.timing(veil,{toValue:0,duration:1400,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.timing(fade,{toValue:1,duration:1000,delay:650,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.timing(rise,{toValue:0,duration:1100,delay:650,easing:Easing.out(Easing.cubic),useNativeDriver:true})]).start();return()=>{float.stop();shimmer.stop();};},[visible,fade,rise,veil,orb,stars]);
 if(!visible)return null;
 const next=()=>{if(line<script.length-1){void cassidyWelcomeEngine.complete();onComplete();return;}Animated.parallel([Animated.timing(fade,{toValue:0,duration:180,useNativeDriver:true}),Animated.timing(rise,{toValue:-12,duration:180,useNativeDriver:true})]).start(()=>{setLine(v=>v+1);rise.setValue(18);Animated.parallel([Animated.timing(fade,{toValue:1,duration:320,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.timing(rise,{toValue:0,duration:420,easing:Easing.out(Easing.cubic),useNativeDriver:true})]).start();});};
 const skip=()=>{void cassidyWelcomeEngine.complete();onComplete()};
 return <View style={styles.root}><Animated.View pointerEvents="none" style={[styles.blackout,{opacity:veil}]}/><View style={styles.sky}><Animated.View style={[styles.moon,{opacity:stars,transform:[{translateY:orb.interpolate({inputRange:[0,1],outputRange:[0,-12]})}]}]}/>{[0,1,2,3,4,5].map(i=><Animated.View key={i} style={[styles.star,{left:`${12+i*15}%`,top:`${15+(i%3)*9}%`,opacity:stars.interpolate({inputRange:[0,1],outputRange:[.25+(i%2)*.2,1]})}]}/>)}</View><Animated.View pointerEvents="none" style={[styles.aura,{opacity:orb.interpolate({inputRange:[0,1],outputRange:[.22,.42]}),transform:[{scale:orb.interpolate({inputRange:[0,1],outputRange:[.9,1.1]})}]}]}/><View style={styles.scene}><Animated.View style={[styles.character,{opacity:fade,transform:[{translateY:orb.interpolate({inputRange:[0,1],outputRange:[4,-4]})}]}]}><CassidyCharacter height={330} action="idle" speaking={line!==script.length-1} expression="warm"/></Animated.View><View style={styles.ground}/></View><Animated.View style={[styles.dialogue,{opacity:fade,transform:[{translateY:rise}]}]}><View style={styles.nameRow}><View style={styles.nameDot}/><Text style={styles.name}>CASSIDY</Text><Text style={styles.meet}>FIRST MEETING</Text></View><Text style={styles.line}>{script[line]}</Text><View style={styles.controls}><Pressable onPress={skip} hitSlop={12} style={styles.skip}><Text style={styles.skipText}>SKIP</Text></Pressable><Pressable onPress={next} style={styles.continue}><Text style={styles.continueText}>{line===script.length-1?'ENTER EMERALD VALLEY':'CONTINUE'}</Text></Pressable></View><View style={styles.progress}>{script.map((_,i)=><View key={i} style={[styles.dot,i<=line&&styles.dotActive]}/>)}</View></Animated.View></View>;
}
const styles=StyleSheet.create({root:{...StyleSheet.absoluteFill,backgroundColor:'#03110d',zIndex:1000},blackout:{...StyleSheet.absoluteFill,backgroundColor:'#020807',zIndex:4},sky:{...StyleSheet.absoluteFill,backgroundColor:'#071c17'},moon:{position:'absolute,width:210,height:210,borderRadius:105,backgroundColor:'#d1fae5',alignSelf:'center',top:'10%',shadowColor:'#6ee7b7',shadowOpacity:.55,shadowRadius:55},star:{position:'absolute',width:3,height:3,borderRadius:2,backgroundColor:'#ecfdf5'},aura:{position:'absolute',width:380,height:380,borderRadius:190,backgroundColor:'#34d399',alignSelf:'center',top:'12%',shadowColor:'#34d399',shadowOpacity:.75,shadowRadius:80},scene:{flex:1,alignItems:'center',justifyContent:'center',paddingBottom:185},character:{alignItems:'center'},ground:{position:'absolute',bottom:160,width:210,height:24,borderRadius:105,backgroundColor:'rgba(52,211,153,.12)'},dialogue:{position:'absolute',left:18,right:18,bottom:22,borderRadius:30,borderWidth:1,borderColor:'rgba(167,243,208,.22)',backgroundColor:'rgba(2,12,9,.95)',padding:22,shadowColor:'#34d399',shadowOpacity:.18,shadowRadius:28},nameRow:{flexDirection:'row',alignItems:'center',marginBottom:10},nameDot:{width:7,height:7,borderRadius:4,backgroundColor:'#6ee7b7',marginRight:8},name:{fontSize:10,fontWeight:'900',letterSpacing:3,color:'#6ee7b7'},meet:{fontSize:8,fontWeight:'700',letterSpacing:1.4,color:'#64748b',marginLeft:10},line:{fontSize:21,lineHeight:30,fontWeight:'600',color:'#f1fdf8',minHeight:92},controls:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:8},skip:{paddingVertical:12,paddingHorizontal:5},skipText:{fontSize:10,fontWeight:'800',letterSpacing:2,color:'#64748b'},continue:{paddingHorizontal:20,paddingVertical:14,borderRadius:20,backgroundColor:'#34d399'},continueText:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#04251b'},progress:{flexDirection:'row',gap:4,marginTop:15},dot:{width:5,height:5,borderRadius:3,backgroundColor:'#334155'},dotActive:{width:15,backgroundColor:'#6ee7b7'}});
