import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Animated,Easing,Pressable,StyleSheet,Text,View} from 'react-native';
import {cassidyWelcomeEngine} from '../../../engines/cassidy/cassidyWelcomeEngine';
export function CassidyFirstMeetingCinematic({visible,onComplete}:{visible:boolean;onComplete:()=>void}){
 const [line,setLine]=useState(0); const fade=useRef(new Animated.Value(0)).current; const rise=useRef(new Animated.Value(28)).current; const glow=useRef(new Animated.Value(.25)).current; const orb=useRef(new Animated.Value(0)).current; const script=useMemo(()=>cassidyWelcomeEngine.script,[]);
 useEffect(()=>{if(!visible)return;setLine(0);fade.setValue(0);rise.setValue(28);glow.setValue(.25);orb.setValue(0);const loop=Animated.loop(Animated.sequence([Animated.timing(orb,{toValue:1,duration:2600,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(orb,{toValue:0,duration:2600,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));loop.start();Animated.parallel([Animated.timing(fade,{toValue:1,duration:900,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.timing(rise,{toValue:0,duration:1100,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.timing(glow,{toValue:1,duration:1600,easing:Easing.out(Easing.quad),useNativeDriver:true})]).start();return()=>loop.stop();},[visible]);
 if(!visible)return null;
 const next=()=>{if(line<script.length-1){void cassidyWelcomeEngine.complete();onComplete();return;}Animated.parallel([Animated.timing(fade,{toValue:0,duration:180,useNativeDriver:true}),Animated.timing(rise,{toValue:-10,duration:180,useNativeDriver:true})]).start(()=>{setLine(v=>v+1);rise.setValue(16);Animated.parallel([Animated.timing(fade,{toValue:1,duration:300,useNativeDriver:true}),Animated.timing(rise,{toValue:0,duration:360,easing:Easing.out(Easing.cubic),useNativeDriver:true})]).start();});};
 const skip=()=>{void cassidyWelcomeEngine.complete();onComplete();};
 return <View style={styles.root}><View style={styles.sky}/><Animated.View pointerEvents="none" style={[styles.aura,{opacity:glow,transform:[{scale:orb.interpolate({inputRange:[0,1],outputRange:[.92,1.08]})}]}]}/><View style={styles.scene}><Animated.View style={[styles.cassidy,{opacity:glow,transform:[{translateY:orb.interpolate({inputRange:[0,1],outputRange:[3,-3]})}]}]}><View style={styles.hair}/><View style={styles.face}><View style={styles.eyeRow}><View style={styles.eye}/><View style={styles.eye}/></View><View style={styles.smile}/></View><View style={styles.body}/><View style={styles.glowHeart}/></Animated.View></View><Animated.View style={[styles.dialogue,{opacity:fade,transform:[{translateY:rise}]}]}><Text style={styles.name}>CASSIDY</Text><Text style={styles.line}>{script[line]}</Text><View style={styles.controls}><Pressable onPress={skip} style={styles.skip}><Text style={styles.skipText}>SKIP INTRO</Text></Pressable><Pressable onPress={next} style={styles.continue}><Text style={styles.continueText}>{line===script.length-1?'ENTER THE WORLD':'CONTINUE'}</Text></Pressable></View><View style={styles.progress}>{script.map((_,i)=><View key={i} style={[styles.dot,i<=line&&styles.dotActive]}/>)}</View></Animated.View></View>;
}
const styles=StyleSheet.create({root:{...StyleSheet.absoluteFillObject,backgroundColor:'#06130f',zIndex:1000},sky:{...StyleSheet.absoluteFillObject,backgroundColor:'#071c17'},aura:{position:'absolute',width:360,height:360,borderRadius:180,backgroundColor:'#34d399',alignSelf:'center',top:'20%',shadowColor:'#34d399',shadowOpacity:.9,shadowRadius:80},scene:{flex:1,alignItems:'center',justifyContent:'center',paddingBottom:160},cassidy:{alignItems:'center'},hair:{width:118,height:128,borderRadius:58,backgroundColor:'#38251e',position:'absolute',top:-8},face:{width:92,height:108,borderRadius:46,backgroundColor:'#f4c7a1',alignItems:'center',paddingTop:42},eyeRow:{flexDirection:'row',gap:27},eye:{width:7,height:9,borderRadius:5,backgroundColor:'#241c1a'},smile:{width:22,height:10,borderBottomWidth:2,borderColor:'#8d5145',borderRadius:12,marginTop:17},body:{width:118,height:140,borderRadius:45,backgroundColor:'#79bfa7',marginTop:-5},glowHeart:{position:'absolute',top:137,width:18,height:18,borderRadius:9,backgroundColor:'#d8fff0'},dialogue:{position:'absolute',left:22,right:22,bottom:32,borderRadius:28,borderWidth:1,borderColor:'rgba(167,243,208,.25)',backgroundColor:'rgba(4,15,12,.94)',padding:22},name:{fontSize:10,fontWeight:'800',letterSpacing:3,color:'#6ee7b7',marginBottom:9},line:{fontSize:22,lineHeight:31,fontWeight:'600',color:'#f1fdf8',minHeight:94},controls:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:12},skip:{paddingVertical:12,paddingHorizontal:5},skipText:{fontSize:9,fontWeight:'700',letterSpacing:1.5,color:'#64748b'},continue:{paddingHorizontal:18,paddingVertical:13,borderRadius:18,backgroundColor:'#34d399'},continueText:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#04251b'},progress:{flexDirection:'row',gap:4,marginTop:15},dot:{width:5,height:5,borderRadius:3,backgroundColor:'#334155'},dotActive:{width:15,backgroundColor:'#6ee7b7'}});
