import type { LanguageWorldId } from '../world/languageWorldEngine';
import type { LearningSkill } from './contextualLanguageLearningEngine';

export type WorldLearningConversationTurn={
 prompt:string;
 targetLanguage:string;
 translation:string;
 vocabulary:{word:string;meaning:string;reading?:string}[];
 responseOptions:{text:string;meaning:string;correct:boolean}[];
};

export type WorldLearningScenario={
 id:string; worldId:LanguageWorldId; placeId:string; area:string; locationType:string; title:string; scene:string;
 skill:LearningSkill; goal:string; targetLanguage:string; translation:string;
 vocabulary:{word:string;meaning:string;reading?:string}[];
 responseOptions:{text:string;meaning:string;correct:boolean}[];
 successWorldChange:string;
 culturalNote?:string;
 followUp?:string;
 continuation?:WorldLearningConversationTurn;
};

const SCENARIOS:WorldLearningScenario[]=[
 {id:'ja-kyoto-tea-order',worldId:'ja',placeId:'kyoto-gion',area:'Gion & Higashiyama',locationType:'small tea shop',title:'Tea in Gion',scene:'Inside a small tea shop in Gion, the owner waits for your order. The room is quiet, and a polite response matters.',skill:'speaking',goal:'Order one tea politely.',targetLanguage:'これをください。',translation:'This one, please.',vocabulary:[{word:'これ',meaning:'this'},{word:'ください',meaning:'please / give me'}],responseOptions:[{text:'これをください。',meaning:'This one, please.',correct:true},{text:'こんにちは。',meaning:'Hello.',correct:false},{text:'わかりません。',meaning:"I don't understand.",correct:false}],successWorldChange:'The owner nods warmly and pours your tea. The shop becomes part of your remembered route.',culturalNote:'Polite, simple requests are useful when interacting with unfamiliar people.',followUp:'Notice how the owner responds and try one more short exchange.',continuation:{prompt:'The owner smiles and asks if you would like to sit here. Answer simply.',targetLanguage:'はい、お願いします。',translation:'Yes, please.',vocabulary:[{word:'はい',meaning:'yes'},{word:'お願いします',meaning:'please / I would like that'}],responseOptions:[{text:'はい、お願いします。',meaning:'Yes, please.',correct:true},{text:'さようなら。',meaning:'Goodbye.',correct:false},{text:'どこですか。',meaning:'Where is it?',correct:false}]}},
 {id:'es-mexico-market-purchase',worldId:'es',placeId:'mexico-city',area:'a neighborhood mercado',locationType:'market stall',title:'A small purchase in the mercado',scene:'A vendor asks what you would like. You recognize the item you want and need to answer naturally.',skill:'speaking',goal:'Ask for one item politely.',targetLanguage:'Quiero esto, por favor.',translation:'I would like this, please.',vocabulary:[{word:'quiero',meaning:'I want / I would like'},{word:'esto',meaning:'this'},{word:'por favor',meaning:'please'}],responseOptions:[{text:'Quiero esto, por favor.',meaning:'I would like this, please.',correct:true},{text:'Buenas noches.',meaning:'Good evening.',correct:false},{text:'No entiendo.',meaning:"I don't understand.",correct:false}],successWorldChange:'The vendor hands you the item. The market becomes part of your remembered route.',culturalNote:'Real markets often require short, practical exchanges rather than long sentences.',followUp:'Listen for the vendor’s next question before choosing your response.',continuation:{prompt:'The vendor asks if you want one more. Answer that you want one.',targetLanguage:'Sí, uno, por favor.',translation:'Yes, one, please.',vocabulary:[{word:'sí',meaning:'yes'},{word:'uno',meaning:'one'}],responseOptions:[{text:'Sí, uno, por favor.',meaning:'Yes, one, please.',correct:true},{text:'Hasta luego.',meaning:'See you later.',correct:false},{text:'No sé.',meaning:'I don’t know.',correct:false}]}},
 {id:'fr-paris-cafe-order',worldId:'fr',placeId:'paris-montmartre',area:'Montmartre',locationType:'neighborhood café',title:'Morning in Montmartre',scene:'At a small Montmartre café, the server asks what you would like. The conversation is brief, but it is happening now.',skill:'speaking',goal:'Order a coffee politely.',targetLanguage:'Je voudrais un café, s’il vous plaît.',translation:'I would like a coffee, please.',vocabulary:[{word:'je voudrais',meaning:'I would like'},{word:'café',meaning:'coffee'},{word:'s’il vous plaît',meaning:'please'}],responseOptions:[{text:'Je voudrais un café, s’il vous plaît.',meaning:'I would like a coffee, please.',correct:true},{text:'Au revoir.',meaning:'Goodbye.',correct:false},{text:'Je ne sais pas.',meaning:"I don't know.",correct:false}],successWorldChange:'The server brings your coffee. You have learned how to enter this everyday situation with language.',culturalNote:'A small café interaction is an opportunity to practice politeness and listening together.',followUp:'Try noticing another natural phrase the server uses.',continuation:{prompt:'The server asks if you would like anything else. Say no, thank you.',targetLanguage:'Non, merci.',translation:'No, thank you.',vocabulary:[{word:'non',meaning:'no'},{word:'merci',meaning:'thank you'}],responseOptions:[{text:'Non, merci.',meaning:'No, thank you.',correct:true},{text:'Bonjour.',meaning:'Hello.',correct:false},{text:'Je voudrais un café.',meaning:'I would like a coffee.',correct:false}]}},
 {id:'ko-busan-market-order',worldId:'ko',placeId:'busan',area:'Jagalchi Market area',locationType:'food stall',title:'Choose your food in Busan',scene:'Near Jagalchi Market, a food-stall owner is ready to take your order while the market moves around you.',skill:'speaking',goal:'Ask for kimbap politely.',targetLanguage:'김밥 주세요.',translation:'Kimbap, please.',vocabulary:[{word:'김밥',meaning:'kimbap'},{word:'주세요',meaning:'please give me'}],responseOptions:[{text:'김밥 주세요.',meaning:'Kimbap, please.',correct:true},{text:'안녕하세요.',meaning:'Hello.',correct:false},{text:'모르겠어요.',meaning:"I don't know.",correct:false}],successWorldChange:'The owner hands over your food. One more real interaction is now part of your experience.',culturalNote:'Short request patterns can be immediately useful in busy everyday situations.',followUp:'Listen for the seller’s response and identify one word you recognize.',continuation:{prompt:'The seller asks if you want anything else. Say no, thank you.',targetLanguage:'아니요, 감사합니다.',translation:'No, thank you.',vocabulary:[{word:'아니요',meaning:'no'},{word:'감사합니다',meaning:'thank you'}],responseOptions:[{text:'아니요, 감사합니다.',meaning:'No, thank you.',correct:true},{text:'주세요.',meaning:'Please give me.',correct:false},{text:'안녕히 가세요.',meaning:'Goodbye.',correct:false}]}}
];

export function getWorldLearningScenarios(worldId:LanguageWorldId,placeId?:string){return SCENARIOS.filter(s=>s.worldId===worldId&&(!placeId||s.placeId===placeId));}
export function getWorldLearningScenario(worldId:LanguageWorldId,placeId:string){return getWorldLearningScenarios(worldId,placeId)[0]??null;}
export function getWorldLearningScenarioById(id:string){return SCENARIOS.find(s=>s.id===id)??null;}
export const worldLearningScenarioEngine={all:()=>SCENARIOS,forWorld:getWorldLearningScenarios,forPlace:getWorldLearningScenario,byId:getWorldLearningScenarioById};
