import { LocalStore } from '../../lib/localStore';
import { languageCapabilityEngine } from './languageCapabilityEngine';
import { worldLearningIntegrationEngine } from './worldLearningIntegrationEngine';
import { worldLearningRelationshipBridge } from '../world/worldLearningRelationshipBridge';
import { getWorldLearningScenarioById } from './worldLearningScenarioEngine';
import { cassidyLearningReactionEngine, type CassidyLearningReaction } from '../cassidy/cassidyLearningReactionEngine';
import { processCassidyInteraction, type CassidyInteractionResult } from '../cassidy/cassidyInteractionLifecycleEngine';
import { worldLearningConsequenceEngine, type WorldLearningConsequence } from '../world/worldLearningConsequenceEngine';

export type WorldLearningFlowResult = {scenarioId:string;success:boolean;capability:Awaited<ReturnType<typeof languageCapabilityEngine.scenario>>;integration:Awaited<ReturnType<typeof worldLearningIntegrationEngine.integrate>>;relationship:Awaited<ReturnType<typeof worldLearningRelationshipBridge.apply>>;cassidy:CassidyLearningReaction;cassidyInteraction:CassidyInteractionResult;world:WorldLearningConsequence};
const COMPLETED_KEY='world_learning_completed_consequences_v1';
const inFlight=new Set<string>();
async function hasCompleted(key:string):Promise<boolean>{const completed=await LocalStore.get<string[]>(COMPLETED_KEY,[]);return Array.isArray(completed)&&completed.includes(key);}
async function rememberCompleted(key:string):Promise<void>{const completed=await LocalStore.get<string[]>(COMPLETED_KEY,[]);const next=Array.isArray(completed)?completed:[];if(!next.includes(key))next.push(key);await LocalStore.set(COMPLETED_KEY,next.slice(-200));}
export async function completeWorldLearningTurn(input:{scenarioId:string;targetLanguage:string;vocabulary:string[];success:boolean;skill?:string}):Promise<Pick<WorldLearningFlowResult,'capability'>>{await languageCapabilityEngine.recordAttempt(input.scenarioId,input.skill);if(input.success)await languageCapabilityEngine.recordSuccess({scenarioId:input.scenarioId,phrase:input.targetLanguage,words:input.vocabulary,skill:input.skill});return{capability:await languageCapabilityEngine.scenario(input.scenarioId)};}
export async function completeWorldLearningFlow(input:{userId:string;scenarioId:string;success:boolean;residentId?:string}):Promise<WorldLearningFlowResult|null>{const{userId,scenarioId,success,residentId}=input;const scenario=getWorldLearningScenarioById(scenarioId);if(!scenario)return null;const key=`${userId}:${scenarioId}:${success?'success':'practice'}`;if(await hasCompleted(key)||inFlight.has(key))return null;inFlight.add(key);try{const turn=await completeWorldLearningTurn({scenarioId,targetLanguage:scenario.targetLanguage,vocabulary:scenario.vocabulary.map(item=>item.word),success,skill:scenario.skill});const integration=await worldLearningIntegrationEngine.integrate(userId,scenarioId,success);if(!integration)return null;const relationship=await worldLearningRelationshipBridge.apply(integration.outcome,residentId);const world=await worldLearningConsequenceEngine.apply(integration.outcome);const cassidyInteraction=await processCassidyInteraction({userId,characterId:'cassidy',interactionId:`world-learning:${scenarioId}:${success?'success':'practice'}`,outcome:success?'success':'neutral',summary:success?`Cassidy witnessed the learner successfully use ${scenario.targetLanguage} for ${scenario.goal} in ${scenario.placeId}.`:`Cassidy witnessed the learner practise ${scenario.goal} in ${scenario.placeId}.`,worldId:scenario.worldId,destinationId:scenario.placeId,activity:'learning'});const cassidy=cassidyLearningReactionEngine.react(integration.outcome,relationship?.relationship?{residentId:relationship.residentId,familiarity:relationship.relationship.familiarity,trust:relationship.relationship.trust,worldEchoId:world.worldEchoId}:{worldEchoId:world.worldEchoId});const result={scenarioId,success,capability:turn.capability,integration,relationship,cassidy,cassidyInteraction,world};await rememberCompleted(key);return result;}finally{inFlight.delete(key);}}
export const worldLearningFlowEngine={complete:completeWorldLearningFlow,completeTurn:completeWorldLearningTurn};
