import React,{useEffect,useRef}from'react';
import{Animated,Text,View}from'react-native';
import{resolvePlaceEnvironment}from'../../../engines/world/placeEnvironmentPresentationEngine';

export function PlaceEnvironmentView({placeId,weather='clear'}:{placeId:string;weather?:string}){
 const environment=resolvePlaceEnvironment(placeId);const drift=useRef(new Animated.Value(0)).current;const glow=useRef(new Animated.Value(0)).current;const rain=useRef(new Animated.Value(0)).current;
 useEffect(()=>{const a=Animated.loop(Animated.sequence([Animated.timing(drift,{toValue:1,duration:7000,useNativeDriver:true}),Animated.timing(drift,{toValue:0,duration:7000,useNativeDriver:true})]));const b=Animated.loop(Animated.sequence([Animated.timing(glow,{toValue:1,duration:3200,useNativeDriver:true}),Animated.timing(glow,{toValue:0,duration:3200,useNativeDriver:true})]));const c=Animated.loop(Animated.timing(rain,{toValue:1,duration:850,useNativeDriver:true}));a.start();b.start();if(weather==='rain')c.start();return()=>{a.stop();b.stop();c.stop();};},[drift,glow,rain,weather]);
 const kind=environment.kind;const architecture=kind==='cafe'?'▰  ▰  ▰':kind==='station'?'▰ ║ ║ ▰':kind==='street'?'⌂   ⌂   ⌂':kind==='shop'?'▣  ▣  ▣':kind==='classroom'?'▥  ▥  ▥':kind==='park'?'♧   ♧   ♧':kind==='market'?'▤  ▤  ▤':kind==='home'?'⌂  ⌂':'·   ·   ·';
 const ground=kind==='station'?'════════════════':kind==='street'?'━━━━━━━━━━━━━━━━':kind==='park'?'⌁  ⌁  ⌁  ⌁':'··············';const actorX=drift.interpolate({inputRange:[0,1],outputRange:[-7,7]});const light=glow.interpolate({inputRange:[0,1],outputRange:[0.04,0.12]});const rainY=rain.interpolate({inputRange:[0,1],outputRange:[-70,420]});
 return <View pointerEvents="none" className="absolute inset-0 overflow-hidden"><View className="absolute inset-0 bg-slate-950"/><View className="absolute inset-x-0 top-0 h-[48%] bg-sky-950/60"/><Animated.View style={{opacity:light}} className="absolute -right-20 top-8 h-56 w-56 rounded-full bg-white"/><Animated.View style={{transform:[{translateX:actorX}]}} className="absolute inset-x-0 top-[31%] h-[22%] items-center justify-center bg-slate-800/45"><Text className="text-5xl font-black tracking-[8px] text-white/10">{architecture}</Text></Animated.View><View className="absolute inset-x-0 bottom-0 h-[48%] bg-slate-950/90"/><View className="absolute inset-x-0 bottom-[28%] items-center"><Text className="text-xl font-black tracking-[6px] text-white/10">{ground}</Text></View><Animated.View style={{transform:[{translateX:actorX}]}} className="absolute inset-x-0 top-[28%] flex-row justify-around px-4">{environment.ambientActors.slice(0,3).map((actor,index)=><View key={`${actor}-${index}`} className="items-center opacity-45"><View className="h-8 w-8 rounded-full bg-white/15"/><View className="mt-1 h-14 w-10 rounded-t-2xl bg-white/10"/><Text className="mt-1 text-[8px] text-white/50">{actor}</Text></View>)}</Animated.View>{weather==='rain'&&<Animated.View style={{transform:[{translateY:rainY}]}} className="absolute inset-x-0 top-0 h-2 bg-white/25"/>}<View className="absolute bottom-[17%] left-5 rounded-2xl border border-white/10 bg-black/25 px-3 py-2"><Text className="text-[9px] font-bold uppercase tracking-[1.5px] text-white/55">{environment.title}</Text><Text className="mt-1 text-[8px] text-white/35">{environment.layers.join(' · ')}</Text></View></View>;
}
export default PlaceEnvironmentView;
