import React,{useMemo,useRef,useState}from'react';
import{Animated,PanResponder,Text,View}from'react-native';
import{CheckCircle2,Move}from'lucide-react-native';
import{isInside,type ActivityItem,type ActivityRect,type ActivityPoint}from'../../../engines/world/worldActivityPrimitives';

export type DragDropTarget={id:string;label:string;rect:ActivityRect};
export type DragDropItem=ActivityItem&{size?:number};

type Props={items:DragDropItem[];targets:DragDropTarget[];onPlaced?:(item:DragDropItem,target:DragDropTarget|null)=>void};

function Draggable({item,targets,onPlaced}:{item:DragDropItem;targets:DragDropTarget[];onPlaced:(item:DragDropItem,target:DragDropTarget|null)=>void}){
 const size=item.size??64;const position=useRef(new Animated.ValueXY({x:item.position.x,y:item.position.y})).current;const origin=useRef(item.position);const[placed,setPlaced]=useState(false);
 const panResponder=useMemo(()=>PanResponder.create({onStartShouldSetPanResponder:()=>!placed,onMoveShouldSetPanResponder:()=>!placed,onPanResponderGrant:()=>{position.setOffset({x:(position.x as any).__getValue(),y:(position.y as any).__getValue()});position.setValue({x:0,y:0})},onPanResponderMove:(_,gesture)=>position.setValue({x:gesture.dx,y:gesture.dy}),onPanResponderRelease:(_,gesture)=>{position.flattenOffset();const point:ActivityPoint={x:origin.current.x+gesture.dx,y:origin.current.y+gesture.dy};const target=targets.find(candidate=>isInside(point,candidate.rect))??null;if(target){setPlaced(true);onPlaced(item,target)}else{Animated.spring(position,{toValue:origin.current,useNativeDriver:false}).start();onPlaced(item,null)}}}),[item,placed,position,targets,onPlaced]);
 return <Animated.View {...panResponder.panHandlers} style={{position:'absolute',left:0,top:0,width:size,height:size,transform:position.getTranslateTransform()}} className={`items-center justify-center rounded-2xl border ${placed?'border-emerald-300/40 bg-emerald-400/15':'border-white/10 bg-slate-900/90'}`}><Move size={14} color={placed?'#a7f3d0':'#94a3b8'}/><Text numberOfLines={2} className="mt-1 px-1 text-center text-[9px] font-bold text-white">{item.label}</Text></Animated.View>
}

export function WorldDragDropBoard({items,targets,onPlaced}:Props){const[score,setScore]=useState(0);const[placed,setPlaced]=useState<Record<string,string>>({});const handlePlaced=(item:DragDropItem,target:DragDropTarget|null)=>{if(!target)return;setPlaced(current=>({...current,[item.id]:target.id}));if(item.correct!==false){setScore(value=>value+100)}onPlaced?.(item,target)};return <View className="w-full rounded-[28px] border border-white/10 bg-white/[0.03] p-4"><View className="mb-4 flex-row items-center justify-between"><View><Text className="text-[10px] font-bold uppercase tracking-[1.4px] text-emerald-200">Drag & drop</Text><Text className="mt-1 text-sm font-bold text-white">Place each clue where it belongs.</Text></View><Text className="text-sm font-black text-emerald-200">{score}</Text></View><View className="relative h-80 overflow-hidden rounded-3xl border border-white/5 bg-slate-950"><View className="absolute inset-0">{targets.map(target=><View key={target.id} style={{position:'absolute',left:target.rect.x,top:target.rect.y,width:target.rect.width,height:target.rect.height}} className={`items-center justify-center rounded-2xl border border-dashed ${placed[target.id]?'border-emerald-300/30 bg-emerald-400/5':'border-white/10 bg-white/[0.02]'}`}><Text className="text-[10px] font-bold text-slate-500">{target.label}</Text>{placed[target.id]?<CheckCircle2 size={13} color="#a7f3d0"/>:null}</View>)}</View>{items.map(item=><Draggable key={item.id} item={item} targets={targets} onPlaced={handlePlaced}/>)}</View></View>}
