import React,{useEffect,useMemo,useState}from'react';
import{Pressable,Text,View}from'react-native';
import{Compass,LockKeyhole,MapPin,Sparkles,Users}from'lucide-react-native';
import{WorldSceneStage}from'./WorldSceneStage';
import{getWorldPlaceHotspots,type WorldPlaceHotspot}from'./worldPlaceHotspotCatalog';
import{worldHotspotRevealEngine}from'../../../engines/world/worldHotspotRevealEngine';
import{getDestinationResidents}from'../../../engines/world/destinationResidentEngine';
import{WorldObjectDiscoveryOverlay}from'../../world/components/WorldObjectDiscoveryOverlay';

const ICONS={landmark:MapPin,resident:Users,discovery:Sparkles,path:Compass,locked:LockKeyhole}as const;
const scopedKey=(placeId:string,hotspotId:string)=>`${placeId}:${hotspotId}`;
export function WorldDestinationExploration({worldId,placeId,onStartScenario,onClose,onCompleteInteraction}:{worldId:any;placeId:string;onStartScenario?:(scenarioKey:string,hotspot?:WorldPlaceHotspot)=>void;onClose?:()=>void;onCompleteInteraction?:(hotspot:WorldPlaceHotspot)=>void|Promise<void>}){
 const[visible,setVisible]=useState<WorldPlaceHotspot[]>([]);const[selected,setSelected]=useState<WorldPlaceHotspot|null>(null);const[busy,setBusy]=useState(false);const[completed,setCompleted]=useState<string[]>([]);const[residentId,setResidentId]=useState<string|undefined>();
 const refresh=async()=>{const state=await worldHotspotRevealEngine.getVisible(placeId);setVisible(state.visible);setCompleted(state.completed);};
 useEffect(()=>{refresh().catch(()=>undefined);},[placeId]);
 const all=useMemo(()=>getWorldPlaceHotspots(placeId),[placeId]);
 const choose=(h:WorldPlaceHotspot)=>{if(busy||h.kind==='locked'||!visible.some(item=>item.id===h.id))return;setSelected(h);};
 const finish=async(hotspot:WorldPlaceHotspot)=>{setBusy(true);try{await onCompleteInteraction?.(hotspot);const result=await worldHotspotRevealEngine.completeAndRevealNext(placeId,hotspot.id);setCompleted(result.progress.completed);setVisible(prev=>result.revealed&&!prev.some(item=>item.id===result.revealed!.id)?[...prev,{...result.revealed,enabled:true}]:prev);if(hotspot.kind==='resident'){const residents=getDestinationResidents(worldId,placeId);const resident=residents[0];if(resident)setResidentId(resident.id);}setSelected(null);}finally{setBusy(false);}};
 const enter=async()=>{if(!selected)return;const hotspot=selected;const scenarioIds=hotspot.scenarioIds??[];if(hotspot.kind==='resident'){const residents=getDestinationResidents(worldId,placeId);const resident=residents[0];if(resident)setResidentId(resident.id);setSelected(null);onStartScenario?.(scenarioIds[0]??hotspot.id,hotspot);return;}if(scenarioIds[0]){setSelected(null);onStartScenario?.(scenarioIds[0],hotspot);return;}await finish(hotspot);};
 return <View className="absolute inset-0 bg-black"><WorldSceneStage worldId={worldId} placeId={placeId} residentId={residentId} showResident={Boolean(residentId)}/><View pointerEvents="none" className="absolute left-5 right-5 top-[8%] z-20"><Text className="text-[9px] font-bold uppercase tracking-[2.5px] text-emerald-300">Explore</Text><Text className="mt-1 text-2xl font-black text-white">Look around before you begin.</Text><Text className="mt-1 max-w-[320px] text-xs leading-5 text-slate-400">Only some parts of this place have opened. Complete one discovery and the world can reveal what comes next.</Text></View><View className="absolute inset-0 z-30" pointerEvents="box-none">{visible.map(h=>{const Icon=ICONS[h.kind];const enabled=h.kind!=='locked'&&h.enabled!==false;const done=completed.includes(scopedKey(placeId,h.id))||completed.includes(h.id);return <Pressable key={h.id} disabled={!enabled} onPress={()=>choose(h)} accessibilityRole="button" accessibilityLabel={`${h.label}${enabled?'':' locked'}`} style={{position:'absolute',left:`${h.x}%`,top:`${h.y}%`,marginLeft:-23,marginTop:-23}}><View className={`h-11 w-11 items-center justify-center rounded-full border ${done?'border-emerald-200/55 bg-emerald-400/25':enabled?'border-emerald-200/35 bg-slate-950/70':'border-white/10 bg-black/50'}`}><Icon size={17} color={enabled?'#a7f3d0':'#64748b'}/></View><Text className={`mt-1 rounded-full bg-black/45 px-2 py-1 text-[9px] font-bold ${enabled?'text-white':'text-slate-500'}`}>{done?'✓ ':''}{h.label}</Text></Pressable>})}</View>{selected&&<WorldObjectDiscoveryOverlay hotspot={selected} onContinue={()=>setSelected(null)} onEnter={enter}/>}<Pressable onPress={onClose} disabled={busy} className="absolute bottom-7 left-5 z-50 rounded-full bg-black/65 px-4 py-2.5"><Text className="text-xs font-semibold text-slate-200">Leave this place</Text></Pressable></View>;
}