import React,{useMemo,useRef,useState}from'react';
import{Animated,PanResponder,Text,View}from'react-native';
import{CheckCircle2,Move}from'lucide-react-native';
import{isInside,type ActivityItem,type ActivityRect,type ActivityPoint}from'../../../engines/world/worldActivityPrimitives';

export type DragDropTarget={id:string;label:string;rect?:ActivityRect;acceptsItemId?:string};
export type DragDropItem=Omit<ActivityItem,'position'>&{position?:ActivityPoint;size?:number};

type Props={items:DragDropItem[];targets:DragDropTarget[];onPlaced?:(item:DragDropItem,target:DragDropTarget|null)=>void;onComplete?:()=>void};

function targetRect(target:DragDropTarget,index:number):ActivityRect{return target.rect??{x:12+(index%2)*150,y:120+Math.floor(index/2)*82,width:132,height:64}}
function itemPoint(item:DragDropItem,index:number):ActivityPoint{return item.position??{x:12+(index%3)*104,y:12+Math.floor(index/3)*62}}

function Draggable({item,index,targets,onPlaced}:{item:DragDropItem;index:number;targets:DragDropTarget[];onPlaced:(item:DragDropItem,target:DragDropTarget|null)=>void}){
 const size=item.size??56;const origin=useMemo(()=>itemPoint(item,index),[item,index]);const position=useRef(new Animated.ValueXY(origin)).current;const[placed,setPlaced]=useState(false);
 const panResponder=useMemo(()=>PanResponder.create({onStartShouldSetPanResponder:()=>!placed,onMoveShouldSetPanResponder:()=>!placed,onPanResponderGrant:()=>{position.setOffset({x:(position.x as any).__getValue(),y:(position.y as any).__getValue()});position.setValue({x:0,y:0})},onPanResponderMove:(_,gesture)=>position.setValue({x:gesture.dx,y:gesture.dy}),onPanResponderRelease:(_,gesture)=>{position.flattenOffset();const point:ActivityPoint={x:origin.x+gesture.dx,y:origin.y+gesture.dy};const target=targets.find((candidate,targetIndex)=>isInside(point,targetRect(candidate,targetIndex))&&(!candidate.acceptsItemId||candidate.acceptsItemId===item.id))??null;if(target){setPlaced(true);onPlaced(item,target)}else{Animated.spring(position,{toValue:origin,useNativeDriver:false}).start();onPlaced(item,null)}}}),[item,index,origin,placed,position,targets,onPlaced]);
 return <Animated.View {...panResponder.panHandlers} style={{position:'absolute',left:0,top:0,width:size,height:size,transform:position.getTranslateTransform()}} className={`items-center justify-center rounded-2xl border ${placed?'border-emerald-300/40 bg-emerald-400/15':'border-white/10 bg-slate-900/90'}`}><Move size={14} color={placed?'#a7f3d0':'#94a3b8'}/><Text numberOfLines={2} className="mt-1 px-1 text-center text-[9px] font-bold text-white">{item.label}</Text></Animated.View>
}

export function WorldDragDropBoard({items,targets,onPlaced,onComplete}:Props){const[score,setScore]=useState(0);const[placed,setPlaced]=useState<Record<string,string>>({});const handlePlaced=(item:DragDropItem,target:DragDropTarget|null)=>{if(!target||placed[item.id])return;setPlaced(current=>{const next={...current,[item.id]:target.id};if(Object.keys(next).length>=items.length)onComplete?.();return next});if(item.correct!==false)setScore(value=>value+100);onPlaced?.(item,target)};return <View className="w-full rounded-[28px] border border-white/10 bg-white/[0.03] p-4"><View className="mb-4 flex-row items-center justify-between"><View><Text className="text-[10px] font-bold uppercase tracking-[1.4px] text-emerald-200">Drag & drop</Text><Text className="mt-1 text-sm font-bold text-white">Place each clue where it belongs.</Text></View><Text className="text-sm font-black text-emerald-200">{score}</Text></View><View className="relative h-80 overflow-hidden rounded-3xl border border-white/5 bg-slate-950">{targets.map((target,index)=>{const rect=targetRect(target,index);const filled=Object.values(placed).includes(target.id);return <View key={target.id} style={{position:'absolute',left:rect.x,top:rect.y,width:rect.width,height:rect.height}} className={`items-center justify-center rounded-2xl border border-dashed ${filled?'border-emerald-300/30 bg-emerald-400/5':'border-white/10 bg-white/[0.02]'}`}><Text className="text-[10px] font-bold text-slate-500">{target.label}</Text>{filled?<CheckCircle2 size={13} color="#a7f3d0"/>:null}</View>})}{items.map((item,index)=><Draggable key={item.id} item={item} index={index} targets={targets} onPlaced={handlePlaced}/>)}</View></View>}
