import React from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
export type AnswerControlMode='idle'|'type'|'speak'|'guidance';
export function WorldExperienceAnswerControls({mode,value,onChange,onSubmit,onType,onSpeak,onGuidance,hint}:{mode:AnswerControlMode;value:string;onChange:(value:string)=>void;onSubmit:()=>void;onType:()=>void;onSpeak:()=>void;onGuidance:()=>void;hint?:string}){
 if(mode==='type')return <View className="absolute inset-x-0 bottom-0 px-4 pb-5 pt-3"><View className="rounded-[24px] border border-white/10 bg-black/65 p-3"><TextInput value={value} onChangeText={onChange} placeholder="Type your answer..." placeholderTextColor="#94a3b8" autoCorrect={false} className="min-h-[46px] rounded-2xl bg-white/10 px-4 py-3 text-base text-white" multiline/><Pressable onPress={onSubmit} className="mt-2 rounded-2xl bg-emerald-500 py-3"><Text className="text-center font-bold text-slate-950">Send answer</Text></Pressable><Pressable onPress={onType} className="mt-2 py-1"><Text className="text-center text-xs text-slate-400">Back to answer options</Text></Pressable></View></View>;
 if(mode==='speak')return <View className="absolute inset-x-0 bottom-0 px-4 pb-5 pt-3"><View className="rounded-[24px] border border-white/10 bg-black/65 p-4"><Text className="text-center text-sm font-bold text-white">🎙️ Speak your answer</Text><Text className="mt-1 text-center text-xs text-slate-400">Voice input can be used when available.</Text><Pressable onPress={onSpeak} className="mt-3 rounded-2xl bg-emerald-500 py-3"><Text className="text-center font-bold text-slate-950">Start / stop speaking</Text></Pressable></View></View>;
 if(mode==='guidance')return <View className="absolute inset-x-0 bottom-0 px-4 pb-5 pt-3"><View className="rounded-[24px] border border-violet-300/15 bg-black/65 p-4"><Text className="text-[10px] font-bold uppercase tracking-[1.5px] text-violet-200">💡 Guidance</Text><Text className="mt-2 text-sm leading-6 text-white">{hint??'Think about what the person needs and use the language you just learned.'}</Text><Pressable onPress={onGuidance} className="mt-3 rounded-2xl bg-white/10 py-3"><Text className="text-center font-bold text-white">Back to answer options</Text></Pressable></View></View>;
 return <View className="absolute inset-x-0 bottom-0 px-4 pb-5 pt-3"><View className="rounded-[24px] border border-white/10 bg-black/55 p-3"><Text className="mb-2 text-center text-[10px] font-bold uppercase tracking-[1.5px] text-white/45">Your turn</Text><View className="flex-row gap-2"><Pressable onPress={onType} className="flex-1 items-center rounded-2xl border border-white/10 bg-white/10 px-2 py-3"><Text className="text-sm font-bold text-white">✍️ Type</Text></Pressable><Pressable onPress={onSpeak} className="flex-1 items-center rounded-2xl border border-white/10 bg-white/10 px-2 py-3"><Text className="text-sm font-bold text-white">🎙️ Speak</Text></Pressable><Pressable onPress={onGuidance} className="flex-1 items-center rounded-2xl border border-white/10 bg-white/10 px-2 py-3"><Text className="text-sm font-bold text-white">💡 Guidance</Text></Pressable></View></View></View>;
}
export default WorldExperienceAnswerControls;
