import React,{useEffect,useState}from'react';
import{Pressable,Text,View,ScrollView}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{ArrowLeft,MapPin,Sparkles,BookOpen}from'lucide-react-native';
import{worldPresenceEngine}from'../../../engines/world/worldPresenceEngine';
import{worldContextEngine}from'../../../engines/world/worldContextEngine';
import{getWorldLearningScenarios,WorldLearningScenario}from'../../../engines/learning/worldLearningScenarioEngine';
import{resolveLanguageWorld}from'../../../engines/world/languageWorldEngine';
interface Props{onStartScenario?:(scenarioKey:string)=>void;onHome?:()=>void;}
export function JourneyWorldScreen({onStartScenario,onHome}:Props){
 const[presence,setPresence]=useState(worldPresenceEngine.current());const[scenario,setScenario]=useState<WorldLearningScenario|null>(null);
 useEffect(()=>{let alive=true;worldPresenceEngine.hydrate().then(next=>{if(!alive)return;setPresence(next);if(next.kind==='journey')setScenario(getWorldLearningScenarios(next.worldId,next.placeId)[0]??null);});return()=>{alive=false;};},[]);
 if(presence.kind!=='journey')return null;const world=resolveLanguageWorld(presence.worldId);const destination=worldContextEngine.resolve(presence).destination;if(!destination)return null;
 return <SafeAreaView className="flex-1 bg-slate-950"><ScrollView className="flex-1" contentContainerStyle={{paddingBottom:130}}><View className="px-5 pt-4"><Pressable onPress={async()=>{await worldPresenceEngine.goHome();onHome?.();}} className="mb-7 flex-row items-center self-start rounded-full border border-white/10 bg-white/5 px-4 py-2"><ArrowLeft size={15} color="#a7f3d0"/><Text className="ml-2 text-xs font-semibold text-emerald-200">Return to Emerald Valley</Text></Pressable><View className="flex-row items-center"><MapPin size={15} color="#6ee7b7"/><Text className="ml-2 text-[10px] font-bold uppercase tracking-[2.5px] text-emerald-300">{world.worldName} · Journey</Text></View><Text className="mt-3 text-4xl font-black text-white">{destination.name}</Text><Text className="mt-2 text-base text-slate-400">{destination.city}, {destination.country}</Text><View className="mt-5 rounded-[28px] border border-white/10 bg-white/[0.04] p-5"><Text className="text-[10px] font-bold uppercase tracking-[2px] text-slate-500">Why you are here</Text><Text className="mt-3 text-sm leading-6 text-slate-300">{destination.description}</Text><View className="mt-4 flex-row flex-wrap">{destination.purpose.split(',').map(item=><View key={item} className="mr-2 mt-2 rounded-full bg-emerald-400/10 px-3 py-1.5"><Text className="text-xs text-emerald-200">{item.trim()}</Text></View>)}</View></View><View className="mt-5 rounded-[28px] border border-violet-300/10 bg-violet-400/[0.05] p-5"><View className="flex-row items-center"><Sparkles size={16} color="#c4b5fd"/><Text className="ml-2 text-[10px] font-bold uppercase tracking-[2px] text-violet-300">A living place</Text></View><Text className="mt-3 text-sm leading-6 text-slate-300">You are not here to collect landmarks. Wander, notice people and places, and let the language become useful because something in this place asks something of you.</Text></View>{scenario&&<View className="mt-5 rounded-[28px] border border-emerald-300/15 bg-emerald-400/[0.05] p-5"><View className="flex-row items-center"><BookOpen size={16} color="#6ee7b7"/><Text className="ml-2 text-[10px] font-bold uppercase tracking-[2px] text-emerald-300">Language moment</Text></View><Text className="mt-3 text-2xl font-black text-white">{scenario.title}</Text><Text className="mt-2 text-sm leading-6 text-slate-300">{scenario.scene}</Text><Text className="mt-4 text-xs font-semibold text-emerald-200">Goal: {scenario.goal}</Text><Pressable onPress={()=>onStartScenario?.(scenario.id)} className="mt-5 items-center rounded-2xl bg-emerald-400/15 px-5 py-4"><Text className="font-bold text-emerald-100">Experience it in {destination.name}</Text></Pressable></View>}</View></ScrollView></SafeAreaView>;
}
