import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, Easing, Pressable, ScrollView, Text, View } from 'react-native';
import { Compass, Eye, Heart, Sparkles, Sun, Moon, CloudRain, MapPin } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useWorldState } from '../../../hooks/useWorldState';
import { LocalStore, CulturalArtifact, RevisitRecord } from '../../../lib/localStore';
import { WaveStore, LivingObject } from '../../../lib/waveStore';
import { eventBus } from '../../../engines/events/eventBus';
import { WonderPromptModal } from '../../learning/components/WonderPromptModal';
import { WorldThresholdModal } from '../components/WorldThresholdModal';
import { EmaRitualModal } from '../components/EmaRitualModal';

interface WorldMapScreenProps { onStartScenario?: (scenarioKey: string) => void; }
type PlaceMood = 'study' | 'cafe' | 'library' | 'market' | 'garden';
interface Place { id: string; key: string; name: string; npcName: string; npcRole: string; description: string; scenarioKey?: string; icon: string; mood: PlaceMood; x: number; y: number; color: string; }
const PLACES: Place[] = [
  { id: 'study-room', key: 'study_room', name: 'Sanctuary', npcName: 'Cassidy', npcRole: 'Companion', description: 'Your quiet home beneath the valley trees.', icon: '⌂', mood: 'study', x: 10, y: 61, color: 'emerald' },
  { id: 'cozy-cafe', key: 'cozy_cafe', name: 'Komorebi Café', npcName: 'Ren', npcRole: 'Barista', description: 'Warm lights, rain on glass, and conversations worth remembering.', scenarioKey: 'scen-cafe-order', icon: '☕', mood: 'cafe', x: 47, y: 34, color: 'amber' },
  { id: 'whispering-library', key: 'whispering_library', name: 'Whispering Library', npcName: 'Emi', npcRole: 'Historian', description: 'Old stories wait between the shelves.', scenarioKey: 'scen-library-inquiry', icon: '▤', mood: 'library', x: 72, y: 16, color: 'violet' },
  { id: 'lantern-market', key: 'lantern_market', name: 'Lantern Market', npcName: 'Kenji', npcRole: 'Stall Master', description: 'A lively evening street where every stall has a story.', scenarioKey: 'scen-market-browse', icon: '🏮', mood: 'market', x: 76, y: 65, color: 'rose' },
  { id: 'zen-garden', key: 'zen_garden', name: 'Whisper Garden', npcName: 'Master Jin', npcRole: 'Garden Keeper', description: 'Bamboo, stone, water, and room to think.', icon: '✦', mood: 'garden', x: 34, y: 78, color: 'sky' },
];
const colorClasses: Record<string, { glow: string; ring: string; text: string; dot: string }> = { emerald: { glow: 'bg-emerald-400/20', ring: 'border-emerald-300/50', text: 'text-emerald-200', dot: 'bg-emerald-300' }, amber: { glow: 'bg-amber-300/20', ring: 'border-amber-300/50', text: 'text-amber-100', dot: 'bg-amber-300' }, violet: { glow: 'bg-violet-300/20', ring: 'border-violet-300/50', text: 'text-violet-100', dot: 'bg-violet-300' }, rose: { glow: 'bg-rose-300/20', ring: 'border-rose-300/50', text: 'text-rose-100', dot: 'bg-rose-300' }, sky: { glow: 'bg-sky-300/20', ring: 'border-sky-300/50', text: 'text-sky-100', dot: 'bg-sky-300' } };
function useBreath(duration: number = 3600) { const value = useRef(new Animated.Value(0)).current; useEffect(() => { const loop = Animated.loop(Animated.sequence([Animated.timing(value, { toValue: 1, duration, easing: Easing.inOut(Easing.sin), useNativeDriver: true }), Animated.timing(value, { toValue: 0, duration, easing: Easing.inOut(Easing.sin), useNativeDriver: true })])); loop.start(); return () => loop.stop(); }, [duration, value]); return value; }
export function WorldMapScreen({ onStartScenario }: WorldMapScreenProps) {
  const { state, changeLocation, worldEngine } = useWorldState();
  const [artifacts, setArtifacts] = useState<CulturalArtifact[]>([]); const [revisitStats, setRevisitStats] = useState<Record<string, RevisitRecord>>({}); const [revisitNotes, setRevisitNotes] = useState<Record<string, string | null>>({}); const [gatedByLoc, setGatedByLoc] = useState<Record<string, number>>({}); const [living, setLiving] = useState<LivingObject[]>([]); const [selectedPlace, setSelectedPlace] = useState<Place | null>(null); const [selectedArtifact, setSelectedArtifact] = useState<CulturalArtifact | null>(null); const [thresholdVisible, setThresholdVisible] = useState(false); const [showEmaModal, setShowEmaModal] = useState(false); const [pendingTarget, setPendingTarget] = useState<Place | null>(null); const breath = useBreath(); const slowBreath = useBreath(6200);
  const loadData = async () => { const nodes = await LocalStore.getKnowledgeNodes(); const gated: Record<string, number> = {}; for (const node of nodes) if (node.masteryLevel < 40) gated[node.locationKey] = (gated[node.locationKey] || 0) + 1; setGatedByLoc(gated); setArtifacts(await LocalStore.getCulturalArtifacts()); setRevisitStats(await LocalStore.getRevisitStats()); const notes: Record<string, string | null> = {}; for (const place of PLACES) notes[place.key] = (await worldEngine.getRevisitDifference(place.key)).note; setRevisitNotes(notes); setLiving(await WaveStore.getLivingObjects()); };
  useEffect(() => { void loadData(); return eventBus.on('world:returned', () => void loadData()); }, []);
  const growth = useMemo(() => Math.round(living.reduce((sum, object) => sum + object.growth, 0)), [living]);
  const currentPlace = PLACES.find(place => place.id === state?.location?.id) ?? PLACES[0];
  const currentWeather = String(state?.weather ?? '').toLowerCase(); const rainy = currentWeather.includes('rain'); const night = (() => { const hour = new Date().getHours(); return hour >= 19 || hour < 6; })();
  const travel = async (place: Place) => { setPendingTarget(place); setThresholdVisible(true); };
  const finishTravel = async () => { if (!pendingTarget) return; await changeLocation(pendingTarget.id); await LocalStore.recordLocationVisit(pendingTarget.key); setThresholdVisible(false); setSelectedPlace(null); setPendingTarget(null); await loadData(); };
  return <SafeAreaView className="flex-1 bg-transparent"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 44 }} className="flex-1"><View className="relative min-h-[780px] overflow-hidden px-5 pt-4"><View pointerEvents="none" className="absolute inset-0 bg-slate-950" /><Animated.View pointerEvents="none" style={{ opacity: breath.interpolate({ inputRange: [0, 1], outputRange: [0.5, 0.9] }) }} className="absolute -right-20 -top-28 h-80 w-80 rounded-full bg-indigo-500/15" /><Animated.View pointerEvents="none" style={{ opacity: slowBreath.interpolate({ inputRange: [0, 1], outputRange: [0.25, 0.55] }) }} className="absolute left-[-80px] top-36 h-72 w-72 rounded-full bg-emerald-400/10" />{Array.from({ length: 18 }).map((_, index) => <Animated.View key={index} pointerEvents="none" style={{ opacity: breath.interpolate({ inputRange: [0, 1], outputRange: [0.18 + (index % 3) * 0.08, 0.55] }) }} className="absolute h-1 w-1 rounded-full bg-white" />)}<View className="z-10 flex-row items-start justify-between"><View className="max-w-[78%]"><View className="flex-row items-center gap-2">{night ? <Moon size={14} color="#c4b5fd" /> : <Sun size={14} color="#fde68a" />}<Text className="text-[10px] font-bold uppercase tracking-[2.5px] text-emerald-300">Emerald Valley</Text></View><Text className="mt-2 text-[30px] font-black tracking-tight text-white">Where will you wander?</Text><Text className="mt-1 text-sm leading-5 text-slate-400">Nothing here is waiting for you to complete it. The valley is simply alive.</Text></View></View></View></ScrollView></SafeAreaView>;
}
