import { LocalStore } from '../../lib/localStore';
import type { CassidyMood } from '../../characters/cassidy';
import type { CassidyLifeActivity } from './cassidyLifeEngine';

const KEY='cassidy:life-state:v1';
export type CassidyLifeState={activity:CassidyLifeActivity;mood:CassidyMood;worldId:string;destinationId?:string;anchorId?:string;startedAt:string;updatedAt:string;visits:number;lastInvitationAt?:string;lastInteractionAt?:string;dreamSeed:number;storySeed:number;adventureSeed:number;};
const ACTIVITIES:ReadonlySet<string>=new Set(['wandering','cafe','reading','watching-rain','stargazing','dreaming','storytelling','adventure','helping','resting','discovering','celebrating']);
const MOODS:ReadonlySet<string>=new Set(['calm','warm','happy','excited','thinking','sad','surprised']);
const DEFAULT_STATE:CassidyLifeState={activity:'resting',mood:'warm',worldId:'emerald-valley',startedAt:new Date(0).toISOString(),updatedAt:new Date(0).toISOString(),visits:0,dreamSeed:17,storySeed:29,adventureSeed:43};
const positiveFinite=(value:unknown,fallback:number)=>typeof value==='number'&&Number.isFinite(value)?Math.max(0,Math.floor(value)):fallback;
function normalize(stored:Partial<CassidyLifeState>):CassidyLifeState{const activity=typeof stored.activity==='string'&&ACTIVITIES.has(stored.activity)?stored.activity as CassidyLifeActivity:DEFAULT_STATE.activity;const mood=typeof stored.mood==='string'&&MOODS.has(stored.mood)?stored.mood as CassidyMood:DEFAULT_STATE.mood;const worldId=typeof stored.worldId==='string'&&stored.worldId.trim()?stored.worldId:DEFAULT_STATE.worldId;return{...DEFAULT_STATE,...stored,activity,mood,worldId,visits:positiveFinite(stored.visits,0),dreamSeed:positiveFinite(stored.dreamSeed,17),storySeed:positiveFinite(stored.storySeed,29),adventureSeed:positiveFinite(stored.adventureSeed,43)};}
export async function getCassidyLifeState():Promise<CassidyLifeState>{const stored=await LocalStore.get<Partial<CassidyLifeState>>(KEY,{});return normalize(stored);}
export async function saveCassidyLifeState(input:Partial<CassidyLifeState>&Pick<CassidyLifeState,'activity'|'mood'|'worldId'>):Promise<CassidyLifeState>{const previous=await getCassidyLifeState();const next=normalize({...previous,...input,updatedAt:new Date().toISOString()});await LocalStore.set(KEY,next);return next;}
export async function beginCassidyLifeMoment(input:{activity:CassidyLifeActivity;mood:CassidyMood;worldId:string;destinationId?:string;anchorId?:string;invitation?:boolean}):Promise<CassidyLifeState>{const previous=await getCassidyLifeState();const now=new Date().toISOString();const changed=previous.activity!==input.activity||previous.worldId!==input.worldId||previous.destinationId!==input.destinationId||previous.anchorId!==input.anchorId;return saveCassidyLifeState({activity:input.activity,mood:input.mood,worldId:input.worldId,destinationId:input.destinationId,anchorId:input.anchorId,startedAt:changed?now:previous.startedAt,visits:previous.visits+(changed?1:0),...(input.invitation?{lastInvitationAt:now}: {})});}
export async function markCassidyInteraction():Promise<CassidyLifeState>{const current=await getCassidyLifeState();return saveCassidyLifeState({activity:current.activity,mood:current.mood,worldId:current.worldId,destinationId:current.destinationId,anchorId:current.anchorId,lastInteractionAt:new Date().toISOString()});}
export async function clearCassidyLifeState():Promise<void>{await LocalStore.set(KEY,DEFAULT_STATE);}
export const cassidyLifeStateEngine={get:getCassidyLifeState,save:saveCassidyLifeState,begin:beginCassidyLifeMoment,markInteraction:markCassidyInteraction,clear:clearCassidyLifeState};
