import type { CassidyLifeActivity } from './cassidyLifeEngine';
import { getCassidyLifeState, saveCassidyLifeState } from './cassidyLifeStateEngine';
import { getCassidyPersonality } from './cassidyPersonalityEngine';
import { createCassidyLifeMoment } from './cassidyLifeDirectorEngine';

export type CassidyPresenceDecision={activity:CassidyLifeActivity;mood:'happy'|'calm'|'thinking'|'excited'|'warm';invitation:boolean;moment?:Awaited<ReturnType<typeof createCassidyLifeMoment>>;};
const activities:CassidyLifeActivity[]=['wandering','cafe','reading','watching-rain','stargazing','dreaming','storytelling','adventure','helping','resting','discovering','celebrating'];
export async function decideCassidyPresence(input:{worldId:string;destinationId?:string;allowStory?:boolean;allowAdventure?:boolean}):Promise<CassidyPresenceDecision>{const state=await getCassidyLifeState();const personality=await getCassidyPersonality();const seed=state.updatedAt||Date.now();let activity=state.worldId===input.worldId&&state.destinationId===input.destinationId?state.activity:activities[Math.abs(seed)%activities.length];if(!input.allowStory&&activity==='storytelling')activity='wandering';if(!input.allowAdventure&&activity==='adventure')activity='discovering';let mood: CassidyPresenceDecision['mood']=personality.adventurousness>75?'excited':personality.curiosity>70?'thinking':personality.warmth>80?'happy':'warm';const invitation=activity==='storytelling'||activity==='adventure'||activity==='helping'||activity==='discovering';let moment: CassidyPresenceDecision['moment'];if(activity==='dreaming'&&input.allowStory)moment=await createCassidyLifeMoment('dream');else if(activity==='storytelling'&&input.allowStory)moment=await createCassidyLifeMoment('story');else if(activity==='adventure'&&input.allowAdventure)moment=await createCassidyLifeMoment('adventure');await saveCassidyLifeState({activity,mood,worldId:input.worldId,destinationId:input.destinationId,lastInvitationAt:invitation?Date.now():state.lastInvitationAt});return {activity,mood,invitation,moment};}
export const cassidyPresenceDirectorEngine={decide:decideCassidyPresence};
