import { LocalStore } from '../../lib/localStore';
import type { CassidyLifeActivity } from './cassidyLifeEngine';
import { getCassidyLifeState, saveCassidyLifeState } from './cassidyLifeStateEngine';
import { MemoryEngine } from '../memory/memoryEngine';
import { evolveCassidyPersonality } from './cassidyPersonalityEngine';

export type CassidyLifeMomentKind='dream'|'story'|'adventure'|'encounter'|'quiet';
export type CassidyLifeMoment={id:string;kind:CassidyLifeMomentKind;title:string;prompt:string;activities:CassidyLifeActivity[];worldId:string;destinationId?:string;createdAt:number;seed:number;memoryRefs:string[];};
const KEY='cassidy_life_moments_v1';
const DREAMS:ReadonlyArray<readonly [string,string]>=[['The Lantern That Remembered','Cassidy dreams of a lantern that lights whenever a forgotten word returns.'],['The Floating Library','Cassidy dreams of a library drifting above the clouds, where every book opens onto a place the learner has visited.'],['Rain on Emerald Valley','Cassidy dreams that the rain speaks in tiny phrases and asks her to listen.'],['The Train Beyond Midnight','Cassidy dreams of a train with no timetable that visits places that do not exist on any map.']];
const STORIES:ReadonlyArray<readonly [string,string]>=[['A Story from the Road','Cassidy found something on her travels and wants to tell you what happened.'],['The Quiet Café','Cassidy remembers a quiet afternoon and turns it into a small story.'],['The Door Behind the Garden','Cassidy discovered a strange door and is curious where it leads.']];
const ADVENTURES:ReadonlyArray<readonly [string,string]>=[['Follow the Lanterns','Cassidy noticed a trail of lanterns leading somewhere unexpected.'],['The Missing Sound','Cassidy heard a sound disappear from a familiar place and wants to investigate.'],['The Map with No North','Cassidy found a map whose directions change when you look away.']];
function pick<T>(a:ReadonlyArray<T>,seed:number):T{return a[Math.abs(Math.floor(seed))%a.length]!;}
function seedNext(seed:number){return(seed*1664525+1013904223)>>>0;}
function seedFor(kind:CassidyLifeMomentKind,state:Awaited<ReturnType<typeof getCassidyLifeState>>){return kind==='dream'?state.dreamSeed:kind==='adventure'?state.adventureSeed:state.storySeed;}
export async function createCassidyLifeMoment(kind:CassidyLifeMomentKind,userId='local-explorer-user'):Promise<CassidyLifeMoment>{const state=await getCassidyLifeState();const now=Date.now();const safeSeed=Number.isFinite(seedFor(kind,state))?seedFor(kind,state):17;const source=kind==='dream'?DREAMS:kind==='adventure'?ADVENTURES:STORIES;const history=await getCassidyLifeMoments();const previousTitles=new Set(history.slice(-6).filter(m=>m.kind===kind).map(m=>m.title));let selected=pick(source,safeSeed);if(previousTitles.size<source.length&&previousTitles.has(selected[0])){for(let i=1;i<source.length+1;i++){const candidate=source[(Math.abs(Math.floor(safeSeed))+i)%source.length]!;if(!previousTitles.has(candidate[0])){selected=candidate;break;}}}const memories=await new MemoryEngine().list(userId);const relevant=memories.filter(memory=>memory.layer==='character'||memory.layer==='world'||memory.layer==='story'||memory.layer==='conversation').slice(0,3);const memoryRefs=relevant.map(memory=>memory.id);const memoryContext=relevant.length?` Cassidy remembers: ${relevant.map(memory=>memory.canonical_fact).join(' | ')}`:'';const activities:CassidyLifeActivity[]=kind==='dream'?['dreaming']:kind==='adventure'?['adventure']:['storytelling'];const moment={id:`cassidy-${kind}-${now}-${safeSeed}`,kind,title:selected[0],prompt:`${selected[1]}${memoryContext}`,activities,worldId:state.worldId,destinationId:state.destinationId,createdAt:now,seed:safeSeed,memoryRefs};await LocalStore.set(KEY,[...history.slice(-19),moment]);await new MemoryEngine().record(userId,'character',`Cassidy experienced ${kind}: ${selected[0]}`,moment.id);await evolveCassidyPersonality({eventId:moment.id,worldId:state.worldId,activity:activities[0],discovery:kind==='adventure',adventure:kind==='adventure'});const seedField=kind==='dream'?'dreamSeed':kind==='adventure'?'adventureSeed':'storySeed';await saveCassidyLifeState({activity:activities[0],mood:kind==='dream'?'thinking':kind==='adventure'?'excited':'warm',worldId:state.worldId,destinationId:state.destinationId,[seedField]:seedNext(safeSeed)});return moment;}
export async function getCassidyLifeMoments():Promise<CassidyLifeMoment[]>{const value=await LocalStore.get<CassidyLifeMoment[]>(KEY,[]);return Array.isArray(value)?value.filter(Boolean):[];}
export const cassidyLifeDirectorEngine={create:createCassidyLifeMoment,list:getCassidyLifeMoments};
