import { LocalStore } from '../../lib/localStore';
import type { CassidyMood } from '../../characters/cassidy';
import type { CassidyLifeActivity } from './cassidyLifeEngine';

const KEY_PREFIX='cassidy:life-state:v2:';
const LEGACY_KEY='cassidy:life-state:v1';
export const CASSIDY_HOME_WORLD_ID='emerald-valley';
export type CassidyLifeState={activity:CassidyLifeActivity;mood:CassidyMood;worldId:string;destinationId?:string;anchorId?:string;startedAt:string;updatedAt:string;visits:number;lastInvitationAt?:string;lastInteractionAt?:string;dreamSeed:number;storySeed:number;adventureSeed:number;};
const ACTIVITIES:ReadonlySet<string>=new Set(['wandering','cafe','reading','watching-rain','stargazing','dreaming','storytelling','adventure','helping','resting','discovering','celebrating']);
const MOODS:ReadonlySet<string>=new Set(['calm','warm','happy','excited','thinking','sad','surprised']);
const DEFAULT_STATE:CassidyLifeState={activity:'resting',mood:'warm',worldId:CASSIDY_HOME_WORLD_ID,startedAt:new Date(0).toISOString(),updatedAt:new Date(0).toISOString(),visits:0,dreamSeed:17,storySeed:29,adventureSeed:43};
const positiveFinite=(value:unknown,fallback:number)=>typeof value==='number'&&Number.isFinite(value)?Math.max(0,Math.floor(value)):fallback;
function keyFor(userId:string){return `${KEY_PREFIX}${userId.trim()}`;}
function normalize(stored:Partial<CassidyLifeState>):CassidyLifeState{const activity=typeof stored.activity==='string'&&ACTIVITIES.has(stored.activity)?stored.activity as CassidyLifeActivity:DEFAULT_STATE.activity;const mood=typeof stored.mood==='string'&&MOODS.has(stored.mood)?stored.mood as CassidyMood:DEFAULT_STATE.mood;const worldId=typeof stored.worldId==='string'&&stored.worldId.trim()?stored.worldId:DEFAULT_STATE.worldId;return{...DEFAULT_STATE,...stored,activity,mood,worldId,visits:positiveFinite(stored.visits,0),dreamSeed:positiveFinite(stored.dreamSeed,17),storySeed:positiveFinite(stored.storySeed,29),adventureSeed:positiveFinite(stored.adventureSeed,43)};}
export async function getCassidyLifeState(userId='local-explorer-user'):Promise<CassidyLifeState>{const safeUserId=userId.trim()||'local-explorer-user';const stored=await LocalStore.get<Partial<CassidyLifeState>>(keyFor(safeUserId),{});if(Object.keys(stored).length)return normalize(stored);if(safeUserId==='local-explorer-user'){const legacy=await LocalStore.get<Partial<CassidyLifeState>>(LEGACY_KEY,{});if(Object.keys(legacy).length){const migrated=normalize(legacy);await LocalStore.set(keyFor(safeUserId),migrated);return migrated;}}return normalize({});}
export async function saveCassidyLifeState(userId:string,input:Partial<CassidyLifeState>&Pick<CassidyLifeState,'activity'|'mood'|'worldId'>):Promise<CassidyLifeState>{const previous=await getCassidyLifeState(userId);const next=normalize({...previous,...input,updatedAt:new Date().toISOString()});await LocalStore.set(keyFor(userId),next);return next;}
export async function beginCassidyLifeMoment(userId:string,input:{activity:CassidyLifeActivity;mood:CassidyMood;worldId:string;destinationId?:string;anchorId?:string;invitation?:boolean}):Promise<CassidyLifeState>{const previous=await getCassidyLifeState(userId);const now=new Date().toISOString();const changed=previous.activity!==input.activity||previous.worldId!==input.worldId||previous.destinationId!==input.destinationId||previous.anchorId!==input.anchorId;return saveCassidyLifeState(userId,{activity:input.activity,mood:input.mood,worldId:input.worldId,destinationId:input.destinationId,anchorId:input.anchorId,startedAt:changed?now:previous.startedAt,visits:previous.visits+(changed?1:0),...(input.invitation?{lastInvitationAt:now}: {})});}
export async function markCassidyInteraction(userId:string,input:{worldId?:string;destinationId?:string;anchorId?:string}={}):Promise<CassidyLifeState>{const current=await getCassidyLifeState(userId);return saveCassidyLifeState(userId,{activity:current.activity,mood:current.mood,worldId:input.worldId??current.worldId,destinationId:input.destinationId??current.destinationId,anchorId:input.anchorId??current.anchorId,lastInteractionAt:new Date().toISOString()});}
export async function clearCassidyLifeState(userId='local-explorer-user'):Promise<void>{await LocalStore.set(keyFor(userId),DEFAULT_STATE);}
export const cassidyLifeStateEngine={get:getCassidyLifeState,save:saveCassidyLifeState,begin:beginCassidyLifeMoment,markInteraction:markCassidyInteraction,clear:clearCassidyLifeState,homeWorldId:CASSIDY_HOME_WORLD_ID};
