import { LocalStore } from '../../lib/localStore';
import type { CassidyLifeActivity } from './cassidyLifeEngine';
import { getCassidyLifeState, saveCassidyLifeState } from './cassidyLifeStateEngine';

export type CassidyLifeMomentKind='dream'|'story'|'adventure'|'encounter'|'quiet';
export type CassidyLifeMoment={id:string;kind:CassidyLifeMomentKind;title:string;prompt:string;activities:CassidyLifeActivity[];worldId:string;destinationId?:string;createdAt:number;seed:number;};
const KEY='cassidy_life_moments_v1';
const DREAMS=[['The Lantern That Remembered','Cassidy dreams of a lantern that lights whenever a forgotten word returns.'],['The Floating Library','Cassidy dreams of a library drifting above the clouds, where every book opens onto a place the learner has visited.'],['Rain on Emerald Valley','Cassidy dreams that the rain speaks in tiny phrases and asks her to listen.'],['The Train Beyond Midnight','Cassidy dreams of a train with no timetable that visits places that do not exist on any map.']];
const STORIES=[['A Story from the Road','Cassidy found something on her travels and wants to tell you what happened.'],['The Quiet Café','Cassidy remembers a quiet afternoon and turns it into a small story.'],['The Door Behind the Garden','Cassidy discovered a strange door and is curious where it leads.']];
const ADVENTURES=[['Follow the Lanterns','Cassidy noticed a trail of lanterns leading somewhere unexpected.'],['The Missing Sound','Cassidy heard a sound disappear from a familiar place and wants to investigate.'],['The Map with No North','Cassidy found a map whose directions change when you look away.']];
function pick<T>(a:T[],seed:number){return a[Math.abs(seed)%a.length];}
function seedNext(seed:number){return (seed*1664525+1013904223)>>>0;}
export async function createCassidyLifeMoment(kind:CassidyLifeMomentKind):Promise<CassidyLifeMoment>{const state=await getCassidyLifeState();const now=Date.now();const seed=kind==='dream'?state.dreamSeed:kind==='adventure'?state.adventureSeed:state.storySeed;const source=kind==='dream'?DREAMS:kind==='adventure'?ADVENTURES:STORIES;const selected=pick(source,seed);const activities:CassidyLifeActivity[]=kind==='dream'?['dreaming']:kind==='adventure'?['adventure','discovering']:['storytelling'];const moment={id:`cassidy-${kind}-${now}-${seed}`,kind,title:selected[0],prompt:selected[1],activities,worldId:state.worldId,destinationId:state.destinationId,createdAt:now,seed};const history=await LocalStore.get<CassidyLifeMoment[]>(KEY,[]);await LocalStore.set(KEY,[...history.slice(-19),moment]);const nextSeed=seedNext(seed);await saveCassidyLifeState({activity:activities[0],mood:kind==='dream'?'thinking':kind==='adventure'?'excited':'warm',worldId:state.worldId,destinationId:state.destinationId,...(kind==='dream'?{dreamSeed:nextSeed}:kind==='adventure'?{adventureSeed:nextSeed}:{storySeed:nextSeed})});return moment;}
export async function getCassidyLifeMoments(){return LocalStore.get<CassidyLifeMoment[]>(KEY,[]);}
export const cassidyLifeDirectorEngine={create:createCassidyLifeMoment,list:getCassidyLifeMoments};
