import type { CassidyLifeActivity } from './cassidyLifeEngine';
import { getCassidyLifeState, saveCassidyLifeState } from './cassidyLifeStateEngine';
import { getCassidyPersonality, moodFromPersonality } from './cassidyPersonalityEngine';
import { createCassidyLifeMoment } from './cassidyLifeDirectorEngine';

export type CassidyPresenceDecision={activity:CassidyLifeActivity;mood:'happy'|'calm'|'thinking'|'excited'|'warm';invitation:boolean;moment?:Awaited<ReturnType<typeof createCassidyLifeMoment>>;};
const ACTIVITIES:CassidyLifeActivity[]=['wandering','cafe','reading','watching-rain','stargazing','dreaming','storytelling','adventure','helping','resting','discovering','celebrating'];
const INVITATION_COOLDOWN_MS=30*60*1000;
export async function decideCassidyPresence(input:{worldId:string;destinationId?:string;allowStory?:boolean;allowAdventure?:boolean}):Promise<CassidyPresenceDecision>{const state=await getCassidyLifeState();const personality=await getCassidyPersonality();const now=Date.now();const stateTime=Date.parse(state.updatedAt);const samePlace=state.worldId===input.worldId&&state.destinationId===input.destinationId;const elapsed=Number.isFinite(stateTime)?Math.max(0,now-stateTime):Infinity;let activity:CassidyLifeActivity=samePlace&&elapsed<15*60*1000?state.activity:ACTIVITIES[Math.abs(now+state.visits)%ACTIVITIES.length]!;if(!input.allowStory&&activity==='storytelling')activity='wandering';if(!input.allowAdventure&&activity==='adventure')activity='discovering';if(activity==='dreaming'&&now%2===0)activity='resting';const mood=moodFromPersonality(personality);const recentlyInvited=Boolean(state.lastInvitationAt&&now-Date.parse(state.lastInvitationAt)<INVITATION_COOLDOWN_MS);const invitation=!recentlyInvited&&(activity==='storytelling'||activity==='adventure'||activity==='helping'||activity==='discovering');let moment: CassidyPresenceDecision['moment'];if(activity==='dreaming'&&input.allowStory)moment=await createCassidyLifeMoment('dream');else if(activity==='storytelling'&&input.allowStory)moment=await createCassidyLifeMoment('story');else if(activity==='adventure'&&input.allowAdventure)moment=await createCassidyLifeMoment('adventure');await saveCassidyLifeState({activity,mood,worldId:input.worldId,destinationId:input.destinationId,lastInvitationAt:invitation?new Date(now).toISOString():state.lastInvitationAt});return{activity,mood,invitation,moment};}
export const cassidyPresenceDirectorEngine={decide:decideCassidyPresence};
