import React, { useEffect, useMemo, useState } from 'react';
import { View, Text, Pressable, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Clock, Heart, MessageCircle, MapPin, Sparkles } from 'lucide-react-native';
import { useCassidy } from '../../../hooks/useCassidy';
import { resolveTimeOfDay } from '../../../lib/time';
type Resident = { key:string;name:string;role:string;avatar:string;location:string;trait:string;mood:string };
const RESIDENTS:Resident[]=[{key:'ren',name:'Ren',role:'Barista',avatar:'☕',location:'Café Komorebi',trait:'Warm, patient, and always experimenting with tea.',mood:'content'},{key:'emi',name:'Emi',role:'Wisdom Keeper',avatar:'📚',location:'Whispering Library',trait:'Collects folktales, idioms, and stories from travelers.',mood:'curious'},{key:'kenji',name:'Kenji',role:'Market Vendor',avatar:'🏮',location:'Lantern Night Market',trait:'Energetic, playful, and impossible to bargain with.',mood:'cheerful'}];
const TIME_LABELS:Record<string,string>={morning:'Morning',afternoon:'Afternoon',evening:'Evening',night:'Night'};
export function CharacterScreen(){const{view}=useCassidy();const[selected,setSelected]=useState<Resident|null>(null);const time=resolveTimeOfDay();const routine=(view?.state?.routine_schedule as Record<string,string>)??{};const activeResidents=useMemo(()=>RESIDENTS.map((resident,index)=>({...resident,mood:index===0&&time==='morning'?'welcoming':resident.mood})),[time]);useEffect(()=>{setSelected(null)},[time]);return <SafeAreaView className="flex-1 bg-transparent"><ScrollView className="flex-1" showsVerticalScrollIndicator={false} contentContainerStyle={{padding:20,paddingBottom:110}}><Text className="text-xs font-semibold uppercase tracking-[2px] text-emerald-400">The Valley · {TIME_LABELS[time]}</Text><Text className="mt-1 text-3xl font-bold text-white">People you may meet</Text><Text className="mt-2 max-w-[340px] text-sm leading-5 text-slate-400">They are not entries in a directory. They are living parts of the world, with places to be and reasons to be there.</Text><View className="mt-7 overflow-hidden rounded-[32px] border border-indigo-400/20 bg-slate-950/55 px-5 py-6"><View className="items-center"><View className="h-24 w-24 items-center justify-center rounded-full border border-indigo-300/30 bg-indigo-400/10"><Text className="text-5xl">🦊</Text></View><Text className="mt-3 text-2xl font-bold text-white">Cassidy</Text><Text className="mt-1 text-center text-sm text-indigo-200">{view?.character?.role??'Your companion through the living world'}</Text><View className="mt-4 flex-row items-center rounded-full bg-emerald-400/10 px-4 py-2"><Sparkles size={14} color="#34d399"/><Text className="ml-2 text-xs font-semibold text-emerald-300">Present · {time}</Text></View></View><View className="mt-6 flex-row justify-around border-t border-white/5 pt-5"><LivingMetric label="Trust" value={view?.relationship?.trust??85}/><LivingMetric label="Friendship" value={view?.relationship?.friendship??80}/><LivingMetric label="Shared" value={Array.isArray(view?.relationship?.shared_history)?view.relationship.shared_history.length:0} suffix=" moments"/></View></View>