import React,{useEffect,useMemo,useRef,useState}from'react';
import{Animated,Easing,Pressable,ScrollView,Text,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{JourneyEngine,JourneyEntry}from'../../../engines/journey/journeyEngine';
import{auth}from'../../../services/auth';
import{LocalStore}from'../../../lib/localStore';
import{getLanguageWorlds,type LanguageWorld}from'../../../engines/world/languageWorldEngine';
import{getLanguageWorldLocation}from'../../world/data/livingLanguageWorldLocations';
import{worldDiscoveryProgressionEngine,type WorldDiscoveryNode}from'../../../engines/world/worldDiscoveryProgressionEngine';
import{Compass,Sparkles,BookOpen,Heart,MapPin,Feather,Plane,Lock,ChevronRight,Star}from'lucide-react-native';
const journeyEngine=new JourneyEngine();
function useFloat(duration=4200){const value=useRef(new Animated.Value(0)).current;useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.timing(value,{toValue:1,duration,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(value,{toValue:0,duration,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));loop.start();return()=>loop.stop();},[duration,value]);return value;}
function canonicalWorldName(world:LanguageWorld){if(world.id==='ja')return'Japanese World';if(world.id==='fr')return'French World';return world.worldName;}
function canonicalRegionLabel(world:LanguageWorld){if(world.id==='ja')return'Real places and fictional learning places across Japan';if(world.id==='fr')return'Real places and fictional learning places across France';return world.regionLabel;}
export function LivingJourneyScreen({onTravel}:{onTravel?:(worldId:string,placeId:string)=>Promise<void>|void}){
 const[timeline,setTimeline]=useState<JourneyEntry[]>([]);const[milestones,setMilestones]=useState<string[]>([]);const[mastered,setMastered]=useState(0);const[showAll,setShowAll]=useState(false);const[selectedWorld,setSelectedWorld]=useState<'ja'|'es'|'fr'|'ko'>('ja');const[nodes,setNodes]=useState<WorldDiscoveryNode[]>([]);const[selected,setSelected]=useState<WorldDiscoveryNode|null>(null);const[travelling,setTravelling]=useState(false);const float=useFloat();const worlds=getLanguageWorlds();const activeWorld=worlds.find(world=>world.id===selectedWorld)??worlds[0];
 useEffect(()=>{const unsub=auth.onAuthStateChange(async user=>{const uid=user?.id??'local-explorer-user';const book=await journeyEngine.buildBook(uid);setTimeline(book.timeline);setMilestones(book.milestones);const knowledge=await LocalStore.getKnowledgeNodes();setMastered(knowledge.filter(node=>node.masteryLevel>=70).length);});return()=>{try{unsub?.data?.subscription?.unsubscribe?.();}catch{}};},[]);
 useEffect(()=>{worldDiscoveryProgressionEngine.get(selectedWorld).then(setNodes).catch(()=>setNodes([]));setSelected(null);},[selectedWorld]);
 const visible=showAll?timeline:timeline.slice(-7);const selectedCanonical=useMemo(()=>selected?getLanguageWorldLocation(selected.placeId):null,[selected]);const selectedPlace=useMemo(()=>selectedCanonical??activeWorld.places.find(place=>place.id===selected?.placeId),[activeWorld,selected,selectedCanonical]);
 const beginJourney=async()=>{if(!selected||selected.status==='locked'||!onTravel||travelling)return;setTravelling(true);try{await onTravel(activeWorld.id,selected.placeId);}finally{setTravelling(false);}};
 return <SafeAreaView className="flex-1 bg-transparent"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:60}}><View className="relative overflow-hidden px-5 pt-5"><View pointerEvents="none" className="absolute inset-0 bg-slate-950"/><Animated.View pointerEvents="none" style={{opacity:float.interpolate({inputRange:[0,1],outputRange:[.18,.42]}),transform:[{translateY:float.interpolate({inputRange:[0,1],outputRange:[14,-14]})}]}} className="absolute -right-24 top-20 h-72 w-72 rounded-full bg-violet-500/15"/><Animated.View pointerEvents="none" style={{opacity:float.interpolate({inputRange:[0,1],outputRange:[.12,.28]})}} className="absolute -left-20 top-80 h-80 w-80 rounded-full bg-emerald-400/10"/><View className="z-10"><View className="flex-row items-center gap-2"><Feather size={15} color="#a7f3d0"/><Text className="text-[10px] font-bold uppercase tracking-[2.5px] text-emerald-300">Your Living Journey</Text></View><Text className="mt-2 text-[31px] font-black tracking-tight text-white">A world you discover.</Text><Text className="mt-2 max-w-[92%] text-sm leading-5 text-slate-400">Choose a language world first. See what exists there, then decide where you want to wander.</Text></View>
 <View className="z-10 mt-6 rounded-3xl border border-emerald-300/10 bg-slate-900/70 p-4"><View className="flex-row items-center gap-2"><Plane size={15} color="#6ee7b7"/><Text className="text-[10px] font-bold uppercase tracking-[2px] text-emerald-300">Choose a living language world</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} className="mt-3 -mx-1" contentContainerStyle={{paddingHorizontal:4,gap:8}}>{worlds.map(world=><Pressable key={world.id} onPress={()=>setSelectedWorld(world.id)} className={`rounded-2xl border px-4 py-2.5 ${selectedWorld===world.id?'border-emerald-300/40 bg-emerald-300/10':'border-white/10 bg-white/5'}`}><Text className={`text-xs font-bold ${selectedWorld===world.id?'text-emerald-200':'text-slate-300'}`}>{canonicalWorldName(world)}</Text><Text className="mt-0.5 text-[9px] text-slate-500">{world.languageName}</Text></Pressable>)}</ScrollView><Text className="mt-3 text-xs leading-5 text-slate-400">{canonicalRegionLabel(activeWorld)}</Text>
 <View className="mt-4 overflow-hidden rounded-[28px] border border-white/10 bg-slate-950/70 p-3"><View className="flex-row items-center justify-between px-1"><View><Text className="text-[9px] font-bold uppercase tracking-[1.8px] text-slate-500">Explore the world</Text><Text className="mt-1 text-sm font-black text-white">{nodes.filter(n=>n.status==='completed').length} discovered · {nodes.filter(n=>n.status==='available').length} available</Text></View><MapPin size={17} color="#6ee7b7"/></View><View className="mt-3 h-[330px] overflow-hidden rounded-[22px] border border-white/5 bg-emerald-950/10"><View pointerEvents="none" className="absolute left-[12%] top-[48%] h-3 w-[75%] rounded-full bg-emerald-300/5 rotate-[-12deg]"/><View pointerEvents="none" className="absolute left-[25%] top-[67%] h-2 w-[55%] rounded-full bg-amber-200/5 rotate-[18deg]"/>{nodes.map((node,index)=>{const x=[50,20,76,40,82,16,61][index%7];const y=[72,54,49,30,20,22,12][index%7];const locked=node.status==='locked';const completed=node.status==='completed';return <Pressable key={node.id} disabled={locked} onPress={()=>setSelected(node)} style={{position:'absolute',left:`${x}%`,top:`${y}%`,marginLeft:-38,marginTop:-38,width:76,height:76}} className="items-center"><View className={`h-14 w-14 items-center justify-center rounded-full border ${completed?'border-emerald-300/45 bg-emerald-400/15':locked?'border-white/5 bg-slate-950/80':'border-amber-200/40 bg-amber-200/10'}`}>{locked?<Lock size={17} color="#475569"/>:completed?<Star size={19} color="#6ee7b7"/>:<MapPin size={19} color="#fcd34d"/>}</View><View className="mt-1 max-w-[92px] rounded-full bg-slate-950/80 px-2 py-1"><Text numberOfLines={1} className={`text-[7px] font-bold ${locked?'text-slate-600':completed?'text-emerald-200':'text-white'}`}>{completed?'✓ ':node.status==='available'?'NEW · ':''}{node.name}</Text></View></Pressable>})}</View></View></View>
 {selected&&<View className="z-20 mt-3 rounded-[26px] border border-white/10 bg-slate-900/95 p-4"><View className="flex-row items-start justify-between"><View className="flex-1 pr-3"><Text className="text-xl font-black text-white">{selected.name}</Text><Text className="mt-1 text-[9px] uppercase tracking-[1.5px] text-emerald-300">{selected.realWorldLocation}</Text></View><Pressable onPress={()=>setSelected(null)}><Text className="text-xl text-slate-500">×</Text></Pressable></View><Text className="mt-3 text-xs leading-5 text-slate-300">{selected.status==='completed'?'You have already experienced this place. It stays in your world for revisits.':`This place is available to discover.${selected.hiddenGem?' There may also be something hidden nearby.':''}`}</Text>{selectedPlace&&<Text className="mt-2 text-[10px] leading-4 text-slate-500">{'description' in selectedPlace?selectedPlace.description:selectedPlace.purpose}</Text>}{selected.status==='available'&&<Pressable onPress={beginJourney} className="mt-4 flex-row items-center justify-center rounded-2xl bg-emerald-400 py-3"><Text className="text-xs font-black text-slate-950">{travelling?'Travelling…':'Enter this location'}</Text><ChevronRight size={16} color="#020617"/></Pressable>}{selected.status==='completed'&&<View className="mt-4 flex-row items-center justify-center rounded-2xl bg-emerald-400/10 py-3"><Text className="text-xs font-semibold text-emerald-200">✓ Discovered · available to revisit</Text></View>}</View>}
 <View className="relative z-10 mt-8 h-[520px]"><View pointerEvents="none" className="absolute left-[50%] top-4 bottom-4 w-px bg-gradient-to-b from-transparent via-emerald-400/30 to-transparent"/>{visible.map((entry,index)=>{const left=index%2===0;const y=18+index*67;return <Animated.View key={entry.id||`${entry.at}-${index}`} style={{top:y,opacity:float.interpolate({inputRange:[0,1],outputRange:[.78,1]}),transform:[{translateY:float.interpolate({inputRange:[0,1],outputRange:[index%2?3:-3,index%2?-3:3]})}]}} className={`absolute w-[46%] ${left?'left-0 items-end pr-4':'right-0 items-start pl-4'}`}><View className="flex-row items-center gap-2"><Text className="max-w-[135px] text-right text-[11px] font-bold text-slate-200">{entry.label}</Text><View className="h-8 w-8 items-center justify-center rounded-full border border-emerald-300/30 bg-slate-950"><Sparkles size={13} color="#6ee7b7"/></View></View><Text className="mt-1 text-[8px] text-slate-500">{new Date(entry.at).toLocaleDateString()}</Text></Animated.View>})}{visible.length===0&&<View className="absolute inset-0 items-center justify-center"><Compass size={34} color="#475569"/><Text className="mt-3 text-sm text-slate-500">Your first light is waiting.</Text></View>}</View><View className="z-10 mt-2 flex-row items-end justify-between"><View><Text className="text-[9px] font-bold uppercase tracking-[1.8px] text-slate-500">Growing knowledge</Text><View className="mt-2 flex-row items-center gap-2"><BookOpen size={17} color="#6ee7b7"/><Text className="text-xl font-black text-white">{mastered}</Text><Text className="text-xs text-slate-400">mastered concepts</Text></View></View><View className="items-end"><Text className="text-[9px] font-bold uppercase tracking-[1.8px] text-slate-500">Memories</Text><View className="mt-2 flex-row items-center gap-2"><Heart size={15} color="#fda4af"/><Text className="text-xl font-black text-white">{timeline.length}</Text></View></View></View></View><View className="mx-5 mt-1">{milestones.length>0&&<View className="flex-row items-center gap-2"><View className="h-2 w-2 rounded-full bg-amber-300"/><Text className="text-xs font-semibold text-amber-200">{milestones[milestones.length-1]}</Text></View>}{timeline.length>7&&<Pressable onPress={()=>setShowAll(v=>!v)} className="mt-4 self-center flex-row items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2"><MapPin size={12} color="#94a3b8"/><Text className="text-[10px] font-bold text-slate-300">{showAll?'Let the newest moments breathe':'Reveal more of the story'}</Text></Pressable>}<Text className="mt-5 text-center text-[10px] italic text-slate-600">Your journey keeps changing while you live it.</Text></View></ScrollView></SafeAreaView>;
}
